#!/usr/bin/env python
# -*- coding: latin-1 -*-
"""
    Random French vocabulary drill
"""

from optparse import OptionParser
from collections import OrderedDict
import operator
import sys
import os
import logging
import random
from datetime import datetime, timezone

class vocab_drill(object):
    def __init__(self, lable, tests):
        self.vocab_name = lable
        self.vocab_array = tests

    def run_drill(self, test_count):
        continue_test = True
        response = "Continue"
        if test_count == 0 or test_count > len(self.vocab_array):
            test_count = len(self.vocab_array)
        v_choices = random.sample(self.vocab_array, test_count)
        index = 0

        print("\n*** STARTING *** %s" % self.vocab_name)
        while response != "Stop" and index < len(v_choices):
            try:
                print("\nTest: %s" % self.vocab_name)
                print("Special chars: \u00E0 \u00E1 \u00E2 \u00E7 \u00E8 \u00E9 \u00EA \u00EC \u00ED \u00EE \u00F2 \u00F3 \u00F4 \u00f9 \u00fa \u00fb")
                v_choice = v_choices[index]
                index = index + 1
                response = input(("French for '%s': " % v_choice[0]))
                if (response == "Stop"):
                    continue_test = False
                    break;
                elif (response == v_choice[1]):
                    print ("Correct!")
                else:
                    print ("Answer for '%s': %s" % (v_choice[0], v_choice[1]))
                    v_choices.append(v_choice)
            except KeyboardInterrupt as KI:
                print("\nExiting...")
                continue_test = False
                break
            except EOFError as EOFE:
                print("\nExiting...")
                continue_test = False
                break
        if continue_test:
            print("\n*** FINISHED *** %s" % self.vocab_name)
        return continue_test

nouns = [ ["the coal", "le charbon"],
          ["the cement", "le ciment"],
          ["the flyash", "les cendres volantes"],
          ["the mine", "la mien"],
          ["the amount", "la montant"],
          ["the electricity", "l'\u00E9lectricit\u00E9"],
          ["the hardwood", "le bois dur"],
          ["the softwood", "le bois tendre"],
          ["the emergency", "l'urgence"],
          ["the tax", "la taxe"],
          ["the taxes", "les imp\u00F4ts"],
          ["the vegetable garden", "le potager"],
          ["the wood chipper", "le broyeur \u00E0 bois"],
          ["the knitting", "le tricotage"],
          ["the flood", "l'inondation"],
          ["the big flood", "la grande inondation"],
          ["today", "aujourd'hui"],
          ["yesterday", "hier"],
          ["tomorrow", "demain"],
          ["the thunder", "le tonnerre"],
          ["the lightning", "l'\u00E9clair"],
          ["the big lightening", "le grand \u00E9clair"],
          ["the basement", "le sous-sol"],
          ["Prince Edward Island", "\u00EEle du prince \u00E9douard"],
          ["other things", "d'autres choses"],
          ["that I can point to", "que je peux montrer du doigt"],
          ["the drawer divider (div)", "le diviseur de tiroir"],
          ["the drawer dividers (sep)", "les s\u00E9parateurs de tiroirs"],
          ["the tree", "l'arbre"],
          ["the shrub", "l'arbuste"],
          ["hindsight", "r\u00E9trospectivement"],
          ["workout", "\u00EAntrainement"],
          ["the weight", "le poids"],
          ["the weights", "les poids"],
          ["early", "t\u00F4t"],
          ["late", "tard"],
          ["the target", "la cible"],
          ["the salesperson", "l'agent de vente"],
          ["the vendor", "le vendeur"],
          ["the business", "les affaires"],
          ["trade", "commerce"],
          ["walkout basement", "sous-sol avec acc\u00E8s direct"],
          ["the goal", "le but"],
          ["knife throwing", "lancer de couteaux"],
          ["axe throwing", "lancer de hache"],
          ["dog sledding", "chien de traineau"],
          ["the firearm", "l'arme \u00E0 feu"],
          ["the small firearm", "la petite arme \u00E0 feu"],
          ["the gun", "le pistolet"],
          ["the pistol", "le pistolet"],
          ["the password", "le mot de passe"],
          ["the username", "le mot d'utilisateur"],
          ["the connection", "le connexion"],
          ["loading", "chargement"],
          ["at race pace", "au rythme de la course"],
          ["a run", "une course"],
          ["the checklist", "la liste de contr\u00f4le"],
          ["first of all", "tout d'abord"],
          ["a car dealership", "un concessionnaire automobile"],
          ["mechanical", "m\u00E9canique"],
          ["mechanic (male)", "m\u00E9canicien"],
          ["mechanic (female)", "m\u00E9canicienne"],
          ["the twig", "la brindille"],
          ["the stem", "la tige"],
          ["the leaf", "la feuille"],
          ["the leaves", "les feuilles"],
          ["the lime", "le citron vert"],
          ["this morning", "ce matin"],
          ["this afternoon", "cet apr\u00E8s midi"],
          ["this evening", "ce soir"],
          ["the hiker", "le randonneur"],
          ["as soon as", "des que"],
          ["it was really cold", "il faisait vraiment froid"],
          ["it was worth it", "\u00e7a en vaut la peine"],
          ["one day at the beginning", "un jour au debut"],
          ["similar", "similaire"],
          ["outskirts", "p\u00e9ripheri\u00e9"],
          ["the suburb", "la banlieue"],
          ["the shirt", "la chemise"],
          ["firstly", "premierement"],
          ["secondly", "deuxi\u00e8mement"],
          ["a hike", "une randonn\u00e9e"],
          ["the car", "la voiture"],
          ["the car I drove", "la voiture que je conduisais"],
          ["the cooler", "le frigo"],
          ["safety systems", "syst\u00e8mes de s\u00e9curit\u00e9"],
          ["the windshield", "le pare-brise"],
          ["the suitcase", "la valise"],
          ["the carry on", "le bagage \u00e0 main"],
          ["the flight attendant", "l'h\u00f4tesse de l'air"],
          ["the big team", "la grande \u00e9quipe"],
          ["the boarding gate", "la porte d'embarquement"],
          ["the box", "la bo\u00EEte"],
          ["a box of food", "une bo\u00EEte de nourriture"],
          ["when we flew to Austrailia", "quand nous avons vol\u00e9 en Australie"],
          ["hard (m)", "dur"],
          ["hard (f)", "dure"],
          ["soft(m)", "doux"],
          ["soft(f)", "douce"],
          ["hit your target", "frappez votre cible"],
          ["an email", "un courriel"],
          ["India", "Inde"],
          ["either one", "n'importe"],
          ["whichever", "n'importe quel"],
          ["whenever", "n'importe quand"],
          ["whatever", "n'importe quoi"],
          ["between", "entre"],
          ["translation", "traduction"],
          ["recording", "enregistrement"],
          ["useful", "utile"],
          ["health", "sant\u00e9"],
          ["Lyme disease", "maladie de Lyme"],
          ["it was bad luck for them", "il etait une mauvaise chance pour eux"],
          ["we attended", "nous sommes all\u00e9s"],
          ["the bride", "la mari\u00e9e"],
          ["the groom", "le mari\u00e9"],
          ["the same as", "pareil"],
          ["a stay", "un s\u00e9jour"],
          ["bilingual", "bilingue"],
          ["the baseball cap", "la casquette de baseball"],
          ["the hat", "le chapeau"],
          ["the maritimes", "les maritimes"],
          ["the big tides", "les grandes mar\u00e9es"],
          ["the still water", "l'eau calme"],
          ["deep", "profond"],
          ["deep waters", "l'eaux profondes"],
          ["fifty feet", "cinquante pieds"],
          ["fifty inches", "cinquante pouces"],
          ["we took the ferry", "nous avons pris le ferry"],
          ["location", "lieu"],
          ["place", "endroit"],
          ["the timing", "le timing"],
          ["remember", "se souvenir"],
          ["church supper", "diner \u00e0 l'\u00e9glise"],
          ["the crab", "le crabe"],
          ["the lobster", "l'homard"],
          ["the scallop", "la p\u00e9toncle"],
          ["the mussel", "la moule"],
          ["the clam", "la palourde"],
          ["the shrimp", "la crevette"],
          ["the dessert", "le dessert"],
          ["I ran", "j'ai couru"],
          ["my back", "mon dos"],
          ["I had a massage (passe compose)", "j'ai eu un massage"],
          ["the stretching", "l'\u00e9tirement"],
          ["a roller coaster", "une montagnes russes"],
          ["terrifying", "terrifiant"],
          ["power plant", "centrale \u00e9lectrique"],
          ["the snow cones", "les cones de neige"],
          ["the brand", "la marque"],
          ["the day", "le jour"],
          ["the workshop", "l'atelier"],
          ["the small workshop", "le petit atelier"],
          ["a meeting", "une r\u00e9union"],
          ["an appointment", "un rendez-vous"],
          ["free time", "temps libre"],
          ["just in case", "au cas o\u00f9"],
          ["a coincidence/fate/luck", "une hasard"],
          ["compared to", "par rapport \u00e0"],
          ["sufficient", "suffisant"],
          ["recommended", "recommand\u00e9"],
          ["that's scary", "\u00e7a c'est effrayent"],
          ["not a single drop", "pas une seule goutte"],
          ["take a break", "pause"],
          ["during the night", "pendant la nuit"],
          ["as for", "quant"],
          ["in my backyard", "dans mon jardin"],
          ["wet", "mouill\u00e9"],
          ["fishing", "\u00e0 la p\u00eache"],
          ["tie-dye", "teinture au noeud"],
          ["delighted/pleased", "ravie"],
          ["flashes", "clignote"],
          ["police search", "perquisition"],
          ["experienced", "exp\u00e9riment\u00e9"],
          ["powerful/potent", "puissant"],
          ["fascinating", "fascinant"],
          ["I could not run uphill", "je ne pouvais pas courir en mont\u00e9e"],
          ["I trained with weights (futur simple)", "je m'entra\u00eenais avec des poids"],
          ["we played golf", "nous jouions du golf"],
          ["spread out", "\u00e9tendu"],
          ["it's nothing (you're welcome)", "de rien"],
          ["welcome", "bienvenue"],
          ["it was nothing (you're welcome)", "il n'y a pas de quoi"],
          ["Welcome to Ottawa", "Bienvenue \u00e0 Ottawa"],
          ["I did not feel well", "je ne me sentais pas bien"],
          ["I think it will be fun for my parents", "Je pense que ce sera amusant pour mes parents"],
          ["The intention was to do a tour of the East coast with them",
           "L'intention \u00e9tait de faire un tour de la c\u00f4te Est avec eux"],
          ["He plays golf very well", "Il joue tr\u00e8s bien au golf"],
          ["the flavour", "la saveur"],
          ["the french cooking", "la cuisine fran\u00e7aise"],
          ["the cooking/baking method", "la cuisson"],
          ["the cooking/baking time", "le temps de cuisson"],
          ["a recipe", "une recette"],
          ["low heat", "feu doux"],
          ["medium heat", "feu moyen"],
          ["high heat", "feu vif"],
          ["a teaspoon (measure)", "une cuill\u00e8re \u00e0 caf\u00e9"],
          ["a tablespoon (measure)", "une cuill\u00e8re \u00e0 soupe"],
          ["the ingredients", "les ingr\u00e9dients"],
          ["the big secret ingredient", "le gros ingr\u00e9dient secret"],
          ["meat served raw", "tartare"],
          ["raw (m)", "cru"],
          ["raw (f)", "crue"],
          ["very rare (meat)", "bleu"],
          ["rare meat (meat)", "saignant"],
          ["medium rare (meat)", "\u00e0 point"],
          ["well done (meat)", "bien cuit"],
          ["a soup stock", "un fond"],
          ["a broth", "un bouillon"],
          ["a hint of", "un soup\u00e7on de"],
          ["the breadcrumbs", "la chapelure"],
          ["the dough/paste", "la p\u00e2te"],
          ["a packet of", "un sachet de"],
          ["baking powder", "la levure chimique"],
          ["the vanilla sugar", "le sucre vanill\u00e9"],
          ["the baking soda", "le bicarbonate de soude"],
          ["an egg yolk", "un jaune d'oeuf"],
          ["the egg whites", "les blancs d'oeufs"],
          ["a bouquet garni", "un bouquet garni"],
          ["home made (m)", "fait maison"],
          ["home made (f)", "faite maison"],
          ["golden brown (m)", "dor\u00e9"],
          ["golden brown (f)", "dor\u00e9e"],
          ["sweet", "sucr\u00e9"],
          ["salty", "sal\u00e9"],
          ["the oven", "le four"],
          ["the stovetop", "la plaque chauffante"],
          ["the stove", "la cuisini\u00e8re"],
          ["the oven tray/baking sheet", "la plaque de cuisson"],
          ["a knife", "un couteau"],
          ["a fork", "une fourchette"],
          ["a spoon", "une cuill\u00e8re"],
          ["a dish", "une assiette"],
          ["a bowl", "un bol"],
          ["a glass", "un verre"],
          ["a mug", "une tasse"],
          ["a frying pan", "une po\u00eale"],
          ["a sauce pan", "une casserole"],
          ["a stew pot", "un fait-tout"],
          ["a lid", "un couvercle"],
          ["a cake mold", "un moule"],
          ["a ladle", "une louche"],
          ["a whisk", "un fouet"],
          ["a rotating whisk", "un batteur"],
          ["a spatula", "une spatule"],
          ["a pressure cooker", "une cocotte-minute"],
          ["a deep fryer", "une friteuse"],
          ["a grater", "une r\u00e2pe"],
          ["an apron", "un tablier"],
          ["a chef's hat", "une toque"],
          ["the chainsaw", "la tron\u00e7onneuse"],
          ["the blade", "la lame"],
          ["apple picking", "cueillette de pommes"],
          ["the apples are spoiled", "les pommes sont g\u00e2t\u00e9es"],
          ["sometimes", "quelquefois"],
          ["unhealthy", "malsain"],
          ["healthy", "sain"],
          ["diabetes", "diab\u00e8te"],
          ["I do not have a sweet tooth", "je n'ai pas la dent sucr\u00e9e"],
          ["habit", "habitude"],
          ["the snack", "le collation"],
          ["temptation", "tentation"],
          ["I want to lose weight", "je veux perdre du poids"],
          ["training (course)", "formation"],
          ["I read the article", "j'ai lu l'article"],
          ["the district", "l'arrondissement"],
          ["the golfer (m)", "le golfeur"],
          ["the golfer (f)", "la golfeuse"],
          ["Tomorrow we will go", "demain nous irons"],
          ["we are going to her friend's house", "nous irons chez son amie"],
          ["dating", "sortir avec"],
          ["a hard run", "une course dure"],
          ["this computer had to have the ability to", "cet ordinateur devait avoir la capacit\u00e9 de"],
          ["bankrupt", "faillite"],
          ["1990", "mille neuf cent quatre-vingt dix"],
          ["second world war", "deuxi\u00e8me guerre mondiale"],
          ["it was a good day", "c'\u00e9tait une bonne journ\u00e9e"],
          ["I rode my bike", "j'ai fait du v\u00e9lo"],
          ["I rode my horse", "j'ai mont\u00e9 mon cheval"],
          ["the small envelope", "la petite enveloppe"],
          ["proud(m)", "fier"],
          ["proud(f)", "fi\u00e8re"],
          ["I am proud of you", "je suis fier de toi"],
          ["for what you get", "pour ce que vous obtenez"],
          ["should/must/have to", "devoir"],
          ["the defect", "le d\u00e9faut"],
          ["far", "loin"],
          ["the small athlete", "le petit athl\u00e8te"],
          ["give me back my toy", "rends-moi mon jouet"],
          ["volunteer (person)", "b\u00e9n\u00e9vole"],
          ["except", "sauf"],
          ["last Saturday", "samedi dernier"],
          ["the ticket", "le billet"],
          ["actually", "en r\u00e9alit\u00e9"],
          ["currently", "actuellement"],
          ["ready for them", "fraiment pour eax"],
          ["consistent(m)", "constant"],
          ["consistent(f)", "constante"],
          ["when he takes the shot", "quand il tire"],
          ["I have not entered the words", "je n'ai pas saisi les mots"],
          ["I didn't think about", "je n'ai pas pens\u00e9"],
          ["the calculation", "le calcul"],
          ["the big computer", "le gros ordinateur"],
          ["the mud", "la boue"],
          ["muddy", "boueuse"],
          ["bugs", "insectes"],
          ["butter chicken", "poulet au beurre"],
          ["breakfast", "petit-d\u00e9jeuner"],
          ["lunch", "d\u00e9jeuner"],
          ["dinner", "d\u00eener"],
          ["the protein", "la prot\u00e9ine"],
          ["strawberry jam", "configures de fraises"],
          ["microwave", "micro-ondes"],
          ["thin", "mince"],
          ["thick(m)", "\u00e9pais"],
          ["thick(f)", "\u00e9paisse"],
          ["measurement", "measure"],
          ["crispy/crunchy", "croquantes"],
          ["make the most of/benefit/enjoy", "profiter"],
          ["more/still", "encore"],
          ["exactly/absolutely/totally/just right/all done", "tout \u00e0 fait"],
          ["the tip", "le pourboire"],
          ["the front nine", "les neuf premiers"],
          ["the back nine", "le neuf de retour"],
          ["when I was a child", "quand j'\u00e9tais un enfant"],
          ["I hate peas", "je d\u00e9teste les pois"],
          ["there are one or two tomatoes that are red", "il y a une ou deux tomates qui sont rouge"],
          ["memories", "souvenirs"],
          ["the soil", "le sol"],
          ["the earth/dirt", "la terre"],
          ["the potting soil", "le terreau"],
          ["beefsteak tomatoes", "tomates coeur de boeuf"],
          ["the wood", "le bois"],
          ["I placed those stones", "j'ai plac\u00e9 ces pierres"],
          ["the electrified fence", "la cl\u00f4ture \u00e9lectrifi\u00e9e"],
          ["the deer", "la cerf"],
          ["high", "haut"],
          ["low", "bas"],
          ["short(m)", "court"],
          ["short(f)", "courte"],
          ["the tulipe", "la tulipe"],
          ["you learned your lesson", "vous avez appris votre le\u00e7on"],
          ["we returned from golf", "nous sommes revenus du golf"],
          ["the root", "la racine"],
          ["the small squirrel", "le petit \u00e9cureuil"],
          ["the fox", "le renard"],
          ["the chipmunk", "le tamia"],
          ["the finger", "le doigt"],
          ["the frost", "le givre"],
          ["the freezer", "la cong\u00e9lateur"],
          ["the grass", "le gazon"],
          ["in the front", "\u00e0 l'avant"],
          ["in the back", "\u00e0 l'arri\u00e8re"],
          ["the mosquitoe", "le moustique"],
          ["the neck guard", "le prot\u00e8ge-cou"],
          ["long-sleeves", "manches longues"],
          ["especially", "surtout"],
          ["sports field", "terrain"],
          ["agricultural field", "champ"],
          ["I'm going to give them away", "je vais les donner"],
          ["I'm going to give them away for free", "je vais les donner gratuitement"],
          ["background (history)", "contexte"],
          ["it looks cheap", "ca a l'air cheap"],
          ["for real professionals", "pour les vrais professionnels"],
          ["the vegetable", "le l\u00e9gume"],
          ["when I freeze them", "quand je les cong\u00e8le"],
          ["ice-cube trays", "plateaux \u00e0 gla\u00e7ons"],
          ["the ice-cube", "le gla\u00e7on"],
          ["the cube", "le cube"],
          ["Ziploc bags", "sacs Ziploc"],
          ["one year (counting)", "un an"],
          ["one year (specific)", "une ann\u00e9e"],
          ["noun", "nom"],
          ["aloud", "\u00e0 haute voix"],
          ["desire/longing", "envie"],
          ["to feel like, to want to", "avoir envie de"],
          ["the swiss chard", "la bette \u00e0 carde"],
          ["they have a really nice place", "ils ont un endroit vraiment beau"],
          ["they have one acre of land", "ils ont un acre de terrain"],
          ["the frog", "la grenouille"],
          ["a cough", "une toux"],
          ["when the sun sets", "quand le soleil se couche"],
          ["I drank (passe compose)", "j'ai bu"],
          ["complicated", "compliqu\u00e0"],
          ["the upper lip", "la l\u00e8vre sup\u00e9rieure"],
          ["when I was a child", "quand j'\u00e9tais enfant"],
          ["I drove", "je conduisais"],
          ["a farmer", "un fermier"],
          ["a maze", "un labyrinthe"],
          ["guinea pig", "cochon d'Inde"],
          ["we should", "nous devrions"],
          ["a pile of compost", "une pile \u00e0 compost"],
          ["a compost heap", "un tas de compost"],
          ["a beet", "une betterave"],
          ["I put the grass", "je mets le gazon"],
          ["layers of compost", "couches de compost"],
          ["special characters", "caract\u00e8res sp\u00e9ciaux"],
          ["what's at stake", "enjeu"],
          ["part/involvement", "implication"],
          ["rallying/mobilization", "mobilisation"],
          ["free vegetables", "l\u00e9gumes gratuits"],
          ["an eggshell", "un coquilles d'ouef"],
          ["I remembered (passe compose)", "je me suis souvenu"],
          ["an award", "un prix"],
          ["when he had to go", "quand il a d\u00fb partir"],
          ["it's not the same", "ce n'est pas la m\u00eame"],
          ["procedure", "proc\u00e9dure"],
          ["a bug (listening device)", "un bug"],
          ["when the police", "quand la police"],
          ["when the police officers", "quand les policiers"],
          ["drug dealers", "trafiquants de drogue"],
          ["in canada", "au canada"],
          ["scientific experiements", "exp\u00e9riences scientifiques"],
          ["safe injection sites", "sites d'injection s\u00fbrs"],
          ["the bottle", "la bouteille"],
          ["immune system", "syst\u00e8me immunitaire"],
          ["alive", "vivant"],
          ["side effects", "effets secondaires"],
          ["pattern", "mod\u00e8le"],
          ["famous", "c\u00e9l\u00e8bre"],
          ["the button", "le bouton"],
          ["a bird", "un oiseau"],
          ["beliefs", "croyances"],
          ["electric cord", "cordon \u00e9lectrique"],
          ["rare/scarce", "rare"],
          ["environmentalist", "\u00e9cologiste"],
          ["it was okay", "c'\u00e9tait acceptable"],
          ["instigated", "g\u00e8re"],
          ["recovery", "r\u00e9cuper\u00e9ration"],
          ["hobby", "passe_temps"],
          ["endgame", "fin de partie"],
          ["market", "march\u00e9"],
          ["to sell on the market", "mettre en vendre"],
          ["a bin", "un bac"],
          ["the plywood", "le contreplaqu\u00e9"],
          ["I am frustrated", "je suis frustr\u00e9"],
          ["frustrating", "frustrant"],
          ["friendly", "amical"],
          ["the lap (body part)", "les genoux"],
          ["take a lap", "faire un tour"],
          ["the floor", "le plancher"],
          ["they(m) live longer", "ils vivent plus longtemps"],
          ["the fur", "le fourrure"],
          ["meowing", "miaulement"],
          ["howling", "hurlement"],
          ["in the middle", "au milieu"],
          ["the sentence", "le phrase"],
          ["and yet", "et pourtant"],
          ["a spider", "une araign\u00e9e"],
          ["spiderwebs", "les toiles d'araign\u00e9e"],
          ["jack-o-lantern", "citrouille-lanternes"],
          ["the pumpkin", "une citrouille"],
          ["surprising", "suprenant"],
          ["surprised(m)", "surpris"],
          ["surprised(f)", "surprise"],
          ["responsible", "responsable"],
          ["curious(m)", "curieux"],
          ["curious(f)", "curieuse"],
          ["kindergarten", "maternelle"],
          ["elementary school", "\u00e9cole primaire"],
          ["middle school", "\u00e9cole interm\u00e9diaire"],
          ["high school", "\u00e9cole secondaire"],
          ["the candle", "la bougie"],
          ["the candlestick", "la bougeoir"],
          ["the map", "la carte"],
          ["climate change", "changement climatique"],
          ["dry(m)", "sec"],
          ["dry(f)", "s\u00e8che"],
          ["redneck", "plouc"],
          ["I practised", "j'ai pratiqu\u00e9"],
          ["I tried", "j'ai essay\u00e9"],
          ["attempted", "tent\u00e9"],
          ["sometimes I was correct", "parfois j'\u00e9tait correct"],
          ["the movie", "le film"],
          ["a suggestion", "une suggestion"],
          ["in fact", "en fait"],
          ["nice", "joli"],
          ["inflate a balloon", "gonfler un ballon"],
          ["blow out a candle", "souffler une bougie"],
          ["the contest", "le concours"],
          ["late in the morning", "en fin de matin\u00e9e"],
          ["would that be okay with you", "est-ce que \u00e7a vous convient"]
          ]

verbs = [ ["to enter/input/grasp/grab/seize/hit", "saisir"],
          ["to type", "taper"],
          ["to spill/tilt/flip", "basculer"],
          ["to cut", "couper"],
          ["to insert", "ins\u00e9rer"],
          ["to include", "inclure"],
          ["to achieve", "atteindre"],
          ["to instigate", "gerer"],
          ["to neuter", "st\u00e9riliser"],
          ["to get/obtain/attain", "obtenir"],
          ["to learn", "apprendre"],
          ["to spoil", "se g\u00e2ter"],
          ["to feel", "sentir"],
          ["to stand out", "se demarquer"],
          ["to wish", "souhaiter"],
          ["to return/give something back", "rendre"],
          ["to swing", "balancer"],
          ["to provide", "fournir"],
          ["to send", "envoyer"],
          ["to lean", "pencher"],
          ["to worry", "s'inqui\u00e8ter"],
          ["to fish", "\u00e0 p\u00eacher"],
          ["to soak", "tremper"],
          ["to remove", "enlever"],
          ["to tell", "raconter"],
          ["to unplug", "debrancher"],
          ["to replug", "rebrancher"],
          ["to restart/reset", "red\u00e9marrer"],
          ["to turn on/light up", "alumer"],
          ["to flash", "clignoter"],
          ["to capture", "capturer"],
          ["to conduct", "mener"],
          ["to enjoy", "appr\u00e9cier"],
          ["to gobble/engulf/wolf down", "engloutir"],
          ["to spread out", "\u00e9tendre"],
          ["to lean on", "appuyer"],
          ["to push on", "appuyer sur"],
          ["to fly", "voler"],
          ["to travel", "voyager"],
          ["to judge", "juger"],
          ["to see", "voir"],
          ["to lose", "perdre"],
          ["to cook/bake", "cuire"],
          ["to warm", "chauffer"],
          ["to preheat", "pr\u00e9chauffer"],
          ["to reheat", "r\u00e9chauffer"],
          ["to bring to a boil", "porter \u00e0 \u00e9bullition"],
          ["to boil", "bouillir"],
          ["to simmer", "mijoter"],
          ["to brown", "faire revenir"],
          ["to put into the oven", "enfourner"],
          ["to melt", "fondre"],
          ["to cook in a frying pan", "po\u00ealer"],
          ["to fry", "frire"],
          ["to reduce", "r\u00e9duire"],
          ["to roast", "r\u00f4tir"],
          ["to steam", "cuire \u00e0 la vapeur"],
          ["to cool", "refroidir"],
          ["to let cool", "laisser refroidir"],
          ["to freeze", "congeler"],
          ["to thaw", "d\u00e9congeler"],
          ["to add", "ajouter"],
          ["to add to other ingredients/again", "rajouter"],
          ["to pour", "verser"],
          ["to stir", "remuer"],
          ["to mix", "m\u00e9langer"],
          ["to whip", "fouetter"],
          ["to mix with a blender", "mixer"],
          ["to slice/chop/carve", "d\u00e9couper"],
          ["to chop", "cisler"],
          ["to slice", "trancher"],
          ["to chop/mince", "hacher"],
          ["to stuff", "farcir"],
          ["to sprinkle/dust", "saupoudrer"],
          ["to coat", "enrober"],
          ["to butter/grease", "beurrer"],
          ["to unmold/remove from a pan", "d\u00e9mouler"],
          ["to grate", "r\u00e2per"],
          ["to peel", "\u00e9plucher"],
          ["to season", "assaisonner"],
          ["to spread", "\u00e9taler"],
          ["to knead", "p\u00e9trir"],
          ["to invest", "investir"],
          ["to let sit", "laisser reposer"],
          ["to volunteer", "se porter voluntaire"],
          ["to follow", "suivre"],
          ["to support", "soutenir"],
          ["to believe", "pour croire"],
          ["to seduce", "s\u00e9duire"],
          ["to crush", "\u00e9craser"],
          ["to recall", "rappeler"],
          ["to cover", "couvrir"],
          ["to kill", "tuer"],
          ["to correct", "corriger"],
          ["to bring/carry/take", "amener"],
          ["to wipe", "essuyer"],
          ["to experiment", "exp\u00e9rimenter"],
          ["to chew", "m\u00e2cher"],
          ["to prevent", "pr\u00e9ventir"],
          ["to maintain", "maintainir"],
          ["to laugh", "rigoler"],
          ["to try", "essayer"],
          ["to practise", "pratiquer"],
          ["to inflate", "gonfler"],
          ["to blow", "souffler"]
          ]

contractions = [ ["\u00e2 le", "au"],
                 ["\u00e2 les", "aux"],
                 ["de le", "du"],
                 ["de les", "des"]
               ]

present_verbs = [ ["I run", "je cours"],
                  ["you run", "tu cours"],
                  ["he runs", "il court"],
                  ["she runs", "elle court"],
                  ["we run", "nous courons"],
                  ["y'all run", "vous courez"],
                  ["they(m) run", "ils courent"],
                  ["they(f) run", "elles courent"],
                  ["I see", "je vois"],
                  ["you see", "tu vois"],
                  ["he sees", "il voit"],
                  ["she sees", "elle voit"],
                  ["we see", "nous voyons"],
                  ["y'all see", "vous voyez"],
                  ["they(m) see", "ils voient"],
                  ["they(f) see", "elles voient"],
                  ["I die", "je meurs"],
                  ["you die", "tu meurs"],
                  ["he dies", "il meurt"],
                  ["she dies", "elle meurt"],
                  ["we die", "nous mourons"],
                  ["y'all die", "vous mourez"],
                  ["they(m) die", "ils meurent"],
                  ["they(f) die", "elles meurent"],
                  ["I can", "je peux"],
                  ["Can I", "puis-je"],
                  ["you can", "tu peux"],
                  ["he can", "il peut"],
                  ["she can", "elle peut"],
                  ["we can", "nous pouvons"],
                  ["y'all can", "vous pouvez"],
                  ["they(m) can", "ils pouvent"],
                  ["they(f) can", "elles pouvent"],
                  ["I send", "j'envoie"],
                  ["you send", "tu envoies"],
                  ["he sends", "il envoie"],
                  ["she sends", "elle envoie"],
                  ["we send", "nous envoyons"],
                  ["y'all send", "vous envoyez"],
                  ["they(m) send", "ils envoient"],
                  ["they(f) send", "elles envoient"],
                  ["I have", "j'ai"],
                  ["you have", "tu as"],
                  ["he has", "il a"],
                  ["she has", "elle a"],
                  ["we have", "nous avons"],
                  ["y'all have", "vous avez"],
                  ["they(m) have", "ils ont"],
                  ["they(f) have", "elles ont"],
                  ["I am", "je suis"],
                  ["you are", "tu es"],
                  ["he is", "il est"],
                  ["she is", "elle est"],
                  ["we are", "nous sommes"],
                  ["y'all are", "vous \u00eates"],
                  ["they(m) are", "ils sont"],
                  ["they(f) are", "elles sont"],
                  ["I do", "je fais"],
                  ["you do", "tu fais"],
                  ["he do", "il fait"],
                  ["she do", "elle fait"],
                  ["we do", "nous faisons"],
                  ["y'all do", "vous faites"],
                  ["they(m) do", "ils font"],
                  ["they(f) do", "elles font"],
                  ["I know", "je sais"],
                  ["you know", "tu sais"],
                  ["he know", "il sait"],
                  ["she know", "elle sait"],
                  ["we know", "nous savons"],
                  ["y'all know", "vous savez"],
                  ["they(m) know", "ils savent"],
                  ["they(f) know", "elles savent"],
                  ["I come", "je viens"],
                  ["you come", "tu viens"],
                  ["he come", "il vient"],
                  ["she come", "elle vient"],
                  ["we come", "nous venons"],
                  ["y'all come", "vous venez"],
                  ["they(m) come", "ils viennent"],
                  ["they(f) come", "elles viennent"],
                  ["I go", "je vais"],
                  ["you go", "tu vas"],
                  ["he goes", "il va"],
                  ["she goes", "elle va"],
                  ["we go", "nous allons"],
                  ["y'all go", "vous allez"],
                  ["they(m) go", "ils vont"],
                  ["they(f) go", "elles vont"]
                ]

imparfait_verbs = [ ["I ran", "je courais"],
                    ["you ran", "tu courais"],
                    ["he ran", "il courait"],
                    ["she ran", "elle courait"],
                    ["we ran", "nous courions"],
                    ["y'all ran", "vous couriez"],
                    ["they(m) ran", "ils couraient"],
                    ["they(f) ran", "elles couraient"],
                    ["I saw", "je voyais"],
                    ["you saw", "tu voyais"],
                    ["he saw", "il voyait"],
                    ["she saw", "elle voyait"],
                    ["we saw", "nous voyions"],
                    ["y'all saw", "vous voyiez"],
                    ["they(m) saw", "ils voyaient"],
                    ["they(f) saw", "elles voyaient"],
                    ["I died", "je mourais"],
                    ["you died", "tu mourais"],
                    ["he died", "il mourait"],
                    ["she died", "elle mourait"],
                    ["we died", "nous mourions"],
                    ["y'all died", "vous mouriez"],
                    ["they(m) died", "ils mouraient"],
                    ["they(f) died", "elles mouraient"],
                    ["I could", "je pouvais"],
                    ["you could", "tu pouvais"],
                    ["he could", "il pouvait"],
                    ["she could", "elle pouvait"],
                    ["we could", "nous pouvions"],
                    ["y'all could", "vous pouviez"],
                    ["they(m) could", "ils pouvaient"],
                    ["they(f) could", "elles pouvaient"],
                    ["I sent", "j'envoyais"],
                    ["you sent", "tu envoyais"],
                    ["he sent", "il envoyait"],
                    ["she sent", "elle envoyait"],
                    ["we sent", "nous envoyions"],
                    ["y'all sent", "vous envoyiez"],
                    ["they(m) sent", "ils envoyaient"],
                    ["they(f) sent", "elles envoyaient"],
                    ["I had", "j'avais"],
                    ["you had", "tu avais"],
                    ["he had", "il avait"],
                    ["she had", "elle avait"],
                    ["we had", "nous avions"],
                    ["y'all had", "vous aviez"],
                    ["they(m) had", "ils avaient"],
                    ["they(f) had", "elles avaient"],
                    ["I was", "j'\u00e9tais"],
                    ["you were", "tu \u00e9tais"],
                    ["he was", "il \u00e9tait"],
                    ["she was", "elle \u00e9tait"],
                    ["we were", "nous \u00e9tions"],
                    ["y'all were", "vous \u00e9tiez"],
                    ["they(m) were", "ils \u00e9taient"],
                    ["they(f) were", "elles \u00e9taient"],
                    ["I did", "je faisais"],
                    ["you did", "tu faisais"],
                    ["he did", "il faisait"],
                    ["she did", "elle faisait"],
                    ["we did", "nous faisions"],
                    ["y'all did", "vous faisiez"],
                    ["they(m) did", "ils faisaient"],
                    ["they(f) did", "elles faisaient"],
                    ["I knew", "je savais"],
                    ["you knew", "tu savais"],
                    ["he knew", "il savait"],
                    ["she knew", "elle savait"],
                    ["we knew", "nous savions"],
                    ["y'all knew", "vous saviez"],
                    ["they(m) knew", "ils savaient"],
                    ["they(f) knew", "elles savaient"],
                    ["I came", "je venais"],
                    ["you came", "tu venais"],
                    ["he came", "il venait"],
                    ["she came", "elle venait"],
                    ["we came", "nous venions"],
                    ["y'all came", "vous veniez"],
                    ["they(m) came", "ils venaient"],
                    ["they(f) came", "elles venaient"],
                    ["I went", "j'allais"],
                    ["you went", "tu allais"],
                    ["he went", "il allait"],
                    ["she went", "elle allait"],
                    ["we went", "nous allions"],
                    ["y'all went", "vous alliez"],
                    ["they(m) went", "ils allaient"],
                    ["they(f) went", "elles allaient"],
                  ]

futur_simple_verbs = [
                    ["I will run", "je courrai"],
                    ["you will run", "tu courras"],
                    ["he will run", "il courra"],
                    ["she will run", "elle courra"],
                    ["we will run", "nous courrons"],
                    ["y'all will run", "vous courrez"],
                    ["they(m) will run", "ils courront"],
                    ["they(f) will run", "elles courront"],
                    ["I will see", "je verrai"],
                    ["you will see", "tu verras"],
                    ["he will see", "il verra"],
                    ["she will see", "elle verra"],
                    ["we will see", "nous verrons"],
                    ["y'all will see", "vous verrez"],
                    ["they(m) will see", "ils verront"],
                    ["they(f) will see", "elles verront"],
                    ["I will die", "je mourrai"],
                    ["you will die", "tu mourras"],
                    ["he will die", "il mourra"],
                    ["she will die", "elle mourra"],
                    ["we will die", "nous mourrons"],
                    ["y'all will die", "vous mourrez"],
                    ["they(m) will die", "ils mourront"],
                    ["they(f) will die", "elles mourront"],
                    ["I could", "je pourrai"],
                    ["you could", "tu pourras"],
                    ["he could", "il pourra"],
                    ["she could", "elle pourra"],
                    ["we could", "nous pourrons"],
                    ["y'all could", "vous pourrez"],
                    ["they(m) could", "ils pourront"],
                    ["they(f) could", "elles pourront"],
                    ["I will send", "j'enverrai"],
                    ["you will send", "tu enverras"],
                    ["he will send", "il enverra"],
                    ["she will send", "elle enverra"],
                    ["we will send", "nous enverrons"],
                    ["y'all will send", "vous enverrez"],
                    ["they(m) will send", "ils enverront"],
                    ["they(f) will send", "elles enverront"],
                    ["I will have", "j'aurai"],
                    ["you will have", "tu auras"],
                    ["he will have", "il aura"],
                    ["she will have", "elle aura"],
                    ["we will have", "nous aurons"],
                    ["y'all will have", "vous aurez"],
                    ["they(m) will have", "ils auront"],
                    ["they(f) will have", "elles auront"],
                    ["I will be", "je serai"],
                    ["you will be", "tu seras"],
                    ["he will be", "il sera"],
                    ["she will be", "elle sera"],
                    ["we will be", "nous serons"],
                    ["y'all will be", "vous serez"],
                    ["they(m) will be", "ils seront"],
                    ["they(f) will be", "elles seront"],
                    ["I will do", "je ferai"],
                    ["you will do", "tu feras"],
                    ["he will do", "il fera"],
                    ["she will do", "elle fera"],
                    ["we will do", "nous ferons"],
                    ["y'all will do", "vous ferez"],
                    ["they(m) will do", "ils feront"],
                    ["they(f) will do", "elles feront"],
                    ["I will know", "je saurai"],
                    ["you will know", "tu sauras"],
                    ["he will know", "il saura"],
                    ["she will know", "elle saura"],
                    ["we will know", "nous saurons"],
                    ["y'all will know", "vous saurez"],
                    ["they(m) will know", "ils sauront"],
                    ["they(f) will know", "elles sauront"],
                    ["I will come", "je viendrai"],
                    ["you will come", "tu viendras"],
                    ["he will come", "il viendra"],
                    ["she will come", "elle viendra"],
                    ["we will come", "nous viendrons"],
                    ["y'all will come", "vous viendrez"],
                    ["they(m) will come", "ils viendront"],
                    ["they(f) will come", "elles viendront"],
                    ["I will go", "j'irai"],
                    ["you will go", "tu iras"],
                    ["he will go", "il ira"],
                    ["she will go", "elle ira"],
                    ["we will go", "nous irons"],
                    ["y'all will go", "vous irez"],
                    ["they(m) will go", "ils iront"],
                    ["they(f) will go", "elles iront"],
                  ]

passe_compose_verbs = [
                    ["I ran", "j'ai couru"],
                    ["you ran", "tu as couru"],
                    ["he ran", "il a couru"],
                    ["she ran", "elle a couru"],
                    ["we ran", "nous avons couru"],
                    ["y'all ran", "vous avez couru"],
                    ["they(m) ran", "ils ont couru"],
                    ["they(f) ran", "elles ont couru"],
                    ["I saw", "j'ai vu"],
                    ["you saw", "tu as vu"],
                    ["he saw", "il a vu"],
                    ["she saw", "elle a vu"],
                    ["we saw", "nous avons vu"],
                    ["y'all saw", "vous avez vu"],
                    ["they(m) saw", "ils ont vu"],
                    ["they(f) saw", "elles ont vu"],
                    ["I died(m)", "je suis mort"],
                    ["you died(m)", "tu es mort"],
                    ["he died(m)", "il est mort"],
                    ["we died(m)", "nous sommes morts"],
                    ["y'all died(m)", "vous \u00eates morts"],
                    ["they(m) died", "ils sont morts"],
                    ["I died(f)", "je suis morte"],
                    ["you died(f)", "tu es morte"],
                    ["she died(f)", "elle est morte"],
                    ["we died(f)", "nous sommes mortes"],
                    ["y'all died(f)", "vous \u00eates mortes"],
                    ["they(f) died", "elles sont mortes"],
                    ["I could", "j'ai pu"],
                    ["you could", "tu as pu"],
                    ["he could", "il a pu"],
                    ["she could", "elle a pu"],
                    ["we could", "nous avons pu"],
                    ["y'all could", "vous avez pu"],
                    ["they(m) could", "ils ont pu"],
                    ["they(f) could", "elles ont pu"],
                    ["I sent", "j'ai envoy\u00e9"],
                    ["you sent", "tu as envoy\u00e9"],
                    ["he sent", "il a envoy\u00e9"],
                    ["she sent", "elle a envoy\u00e9"],
                    ["we sent", "nous avons envoy\u00e9"],
                    ["y'all sent", "vous avez envoy\u00e9"],
                    ["they(m) sent", "ils ont envoy\u00e9"],
                    ["they(f) sent", "elles ont envoy\u00e9"],
                    ["I had", "j'ai eu"],
                    ["you had", "tu as eu"],
                    ["he had", "il a eu"],
                    ["she had", "elle a eu"],
                    ["we had", "nous avons eu"],
                    ["y'all had", "vous avez eu"],
                    ["they(m) had", "ils ont eu"],
                    ["they(f) had", "elles ont eu"],
                    ["I was", "j'ai \u00e9t\u00e9"],
                    ["you were", "tu as \u00e9t\u00e9"],
                    ["he was", "il a \u00e9t\u00e9"],
                    ["she was", "elle a \u00e9t\u00e9"],
                    ["we were", "nous avons \u00e9t\u00e9"],
                    ["y'all were", "vous avez \u00e9t\u00e9"],
                    ["they(m) were", "ils ont \u00e9t\u00e9"],
                    ["they(f) were", "elles ont \u00e9t\u00e9"],
                    ["I did", "j'ai fait"],
                    ["you did", "tu as fait"],
                    ["he did", "il a fait"],
                    ["she did", "elle a fait"],
                    ["we did", "nous avons fait"],
                    ["y'all did", "vous avez fait"],
                    ["they(m) did", "ils ont fait"],
                    ["they(f) did", "elles ont fait"],
                    ["I knew", "j'ai su"],
                    ["you knew", "tu as su"],
                    ["he knew", "il a su"],
                    ["she knew", "elle a su"],
                    ["we knew", "nous avons su"],
                    ["y'all knew", "vous avez su"],
                    ["they(m) knew", "ils ont su"],
                    ["they(f) knew", "elles ont su"],
                    ["I came(m)", "je suis venu"],
                    ["you came(m)", "tu es venu"],
                    ["he came(m)", "il est venu"],
                    ["she came(m)", "elle est venu"],
                    ["we came(m)", "nous sommes venus"],
                    ["y'all came(m)", "vous \u00eates venus"],
                    ["they(m) came(m)", "ils sont venus"],
                    ["I came(f)", "je suis venue"],
                    ["you came(f)", "tu es venue"],
                    ["she came(f)", "elle est venue"],
                    ["we came(f)", "nous sommes venues"],
                    ["y'all came(f)", "vous \u00eates venues"],
                    ["they(f) came(f)", "elles sont venues"],
                    ["I went(m)", "je suis all\u00e9"],
                    ["you went(m)", "tu es all\u00e9"],
                    ["he went(m)", "il est all\u00e9"],
                    ["we went(m)", "nous sommes all\u00e9s"],
                    ["y'all went(m)", "vous \u00eates all\u00e9s"],
                    ["they(m) went", "ils sont all\u00e9s"],
                    ["I went(f)", "je suis all\u00e9e"],
                    ["you went(f)", "tu es all\u00e9e"],
                    ["she went(f)", "elle est all\u00e9e"],
                    ["we went(f)", "nous sommes all\u00e9es"],
                    ["y'all went(f)", "vous \u00eates all\u00e9es"],
                    ["they(f) went", "elles sont all\u00e9es"],
                  ]


class run_vocab_drill(object):
    def __init__(self, options):
        self.nouns = vocab_drill("Nouns, adjectives, adverbs", nouns)
        self.verbs = vocab_drill("Verbs", verbs)
        self.present_verbs = vocab_drill("Present verbs",
                                          present_verbs)
        self.imparfait_verbs = vocab_drill("Imparfait verbs",
                                            imparfait_verbs)
        self.futur_simple_verbs = vocab_drill("Futur simple verbs",
                                               futur_simple_verbs)
        self.contractions = vocab_drill("Contractions",
                                         contractions)
        self.passe_compose_verbs = vocab_drill("Passe compose verbs",
                                                passe_compose_verbs)
        self.drills = []
        if options.general_vocab:
            self.drills.append(self.nouns)
        if options.verbs:
            self.drills.append(self.verbs)
        if options.present_tense:
            self.drills.append(self.present_verbs)
        if options.imparfait_tense:
            self.drills.append(self.imparfait_verbs)
        if options.futur_simple:
            self.drills.append(self.futur_simple_verbs)
        if options.passe_compose:
            self.drills.append(self.passe_compose_verbs)
        if options.contractions:
            self.drills.append(self.contractions)
        self.sample_size = options.sample_size

    def run_drill(self):
        drill_count = 0
        continue_drill = True
        while (continue_drill):
            drill_types = random.sample(self.drills, len(self.drills))
            for drill_type in drill_types:
                continue_drill = drill_type.run_drill(self.sample_size)
                if not continue_drill:
                    break
            if continue_drill:
                drill_count = drill_count + 1
                print("\n***>>> Completed all drills for round %d. <<<***\n"
                        % drill_count)

def create_parser():
    parser = OptionParser(description="French vocabulary and verb conjugation drill.  Default settings ask 5 random questions in every area.  The order of the areas is randomized.  All questions for an area must be answered correctly before the next area is started.          Enter 'Stop' or CTRL<D> to exit the drill.")
    parser.add_option("-g", "--general",
                      action="store_true", dest="general_vocab", default=False,
                      help="general vocabulary (nouns, adjectives)")
    parser.add_option("-v", "--verbs",
                      action="store_true", dest="verbs", default=False,
                      help="verbs infinitif")
    parser.add_option("-p", "--present",
                      action="store_true", dest="present_tense", default=False,
                      help="conjugate verbs in present tense")
    parser.add_option("-f", "--future",
                      action="store_true", dest="futur_simple", default=False,
                      help="conjugate verbs in futur simple")
    parser.add_option("-i", "--imparfait",
                      action="store_true", dest="imparfait_tense", default=False,
                      help="conjugate verbs in imparfait")
    parser.add_option("-c", "--passe_compose",
                      action="store_true", dest="passe_compose", default=False,
                      help="conjugate verbs in passe compose")
    parser.add_option("-C", "--contractions",
                      action="store_true", dest="contractions", default=False,
                      help="check vocabulary of french contractions")
    parser.add_option("-s", "--sample_size", type="int",
                      dest="sample_size", default=5,
                      help="set sample size for each test")
    return parser

def check_options(options):
    if (not options.present_tense and not options.futur_simple and
        not options.imparfait_tense and not options.passe_compose and
        not options.general_vocab and not options.contractions and
        not options.verbs ):
        options.general_vocab = True
        options.verbs = True
        options.present_tense = True
        options.futur_simple = True
        options.imparfait_tense = True
        options.passe_compose = True
        options.contractions = True
    else:
       # If at least one tense was requested,
       # set the default sample size is check all verbs for each tense.
       if options.sample_size == 5:
           options.sample_size = 0

def main(argv = None):
    logging.basicConfig(level=logging.INFO)
    parser = create_parser()
    if argv is None:
        argv = sys.argv[1:]

    (options, argv) = parser.parse_args(argv)
    if len(argv) != 0:
        print('Must enter at least one thing!')
        print
        parser.print_help()
        return -1

    check_options(options)

    drill = run_vocab_drill(options)
    drill.run_drill()

if __name__ == '__main__':
    sys.exit(main())
