#!/usr/bin/env python
# -*- coding: latin-1 -*-
"""
    Random French vocabulary drill
"""

from optparse import OptionParser
from collections import OrderedDict
import operator
import sys
import os
import logging
import random
from datetime import datetime, timedelta
import math

class vocab_drill(object):
    def __init__(self, lable, tests):
        self.vocab_name = lable
        self.vocab_array = tests
        self.special_chars = [ ["/\\a", "\u00E2"], # a circumflex
                               [  "/a", "\u00E1"], # a accent ague
                               [ "\\a", "\u00E0"], # a accent grave
                               [ "\/c", "\u00E7"], # c cedilla
                               ["/\\e", "\u00EA"], # e circumflex
                               [  "/e", "\u00E9"], # e accent ague
                               [ "\\e", "\u00E8"], # e accent grave
                               ["/\\i", "\u00EE"], # i circumflex
                               [  "/i", "\u00ED"], # i accent ague
                               [ "\\i", "\u00EC"], # i accent grave
                               ["/\\o", "\u00F4"], # o circumflex
                               [  "/o", "\u00F3"], # o accent ague
                               [ "\\o", "\u00F2"], # o accent grave
                               ["/\\u", "\u00FB"], # u circumflex
                               [  "/u", "\u00FA"], # u accent ague
                               [ "\\u", "\u00F9"], # u accent grave
                               ]

    def convert_response(self, raw_response):
        response = raw_response
        for old, new_str in self.special_chars:
            response = response.replace(old, new_str)
        return response

    def special_chars_list(self):
        return [spec_char[1] for spec_char in self.special_chars]

    def run_drill(self, test_count):
        continue_test = True
        response = "Continue"
        if test_count == 0 or test_count > len(self.vocab_array):
            test_count = len(self.vocab_array)
        v_choices = random.sample(self.vocab_array, test_count)
        index = 0

        print("\n*** STARTING *** %s" % self.vocab_name)
        while response != "Stop" and index < len(v_choices):
            try:
                print("\nTest: %s" % self.vocab_name)
                print("Special chars: %s" % " ".join(self.special_chars_list()))
                v_choice = v_choices[index]
                index = index + 1
                raw_response = input(("French   for '%s': " % v_choice[0]))
                response = self.convert_response(raw_response)
                if (not raw_response == response):
                    print ("Response for '%s': %s" % (v_choice[0], response))
                if (response == "Stop"):
                    continue_test = False
                    break;
                elif (response == v_choice[1]) or (response == "DROP IT"):
                    print ("Correct!")
                else:
                    print ("Answer   for '%s': %s" % (v_choice[0], v_choice[1]))
                    v_choices.append(v_choice)
            except KeyboardInterrupt as KI:
                print("\nExiting...")
                continue_test = False
                break
            except EOFError as EOFE:
                print("\nExiting...")
                continue_test = False
                break
        if continue_test:
            print("\n*** FINISHED *** %s" % self.vocab_name)
        return continue_test

phrases = [
          ["but their commitment is admirable", "mais leur engagement est admirable"],
          ["to get good grades", "avoir de bonnes notes"],
          ["to be bad at", "\u00eatre poche en"],
          ["physical education", "l'\u00e9ducation physique"],
          ["anyway", "en tous cas"],
          ["in any case", "dans tous les cas"],
          ["after every question", "apr\u00e8s chaque question"],
          ["ear drops", "gouttes pour les oreilles"],
          ["what I was going to say", "qu'est que j'allais dire"],
          ["spoken history - histoire parl\u00e9e"],
          ["half of the boats", "la moiti/u00e9 des bateaux"],
          ["we will fly", "nous volerons"],
          ["a world wonder", "une merveille du monde"],
          ["I hope to visit", "j'esp\u00e8re visiter"],

          ["through", "\u00e0 travers"],
          ["wear a thin jacket", "porter une veste fine"],
          ["wear shorts", "porter des shorts"],
          ["I take care of myself", "je prends soin de moi"],
          ["it is not the same", "ce n'est pas pareil"],
          ["to get rid of", "se d\u00e9barrasser de"],
          ["to come back into fashion", "revenir \u00e0 la mode"],
          ["at the bottom", "dans le fond"],
          ["occasionally", "\u00e0 l'occasion"],
          ["have you ever seen", "tu as d\u00e9j\u00e0 vu"],
          ["to hit the ground", "taper la terre"],
          ["full lips", "des l\u00e8vres pulpeuses"],
          ["young women prefer quite a thin nose", "les jeunes femmes pr\u00e9f\u00e8rent un nez assez fin"],
          ["arched eyebrows", "des sourcils arqu\u00e9s"],
          ["high cheekbones", "des pommettes saillantes"],
          ["muddy boots", "bottes boueuses"],
          ["muddy hats", "chapeaux boueux"],
          ["from time to time", "de temps en temps"],
          ["at sunrise", "au lever du soleil"],
          ["a fishing village", "une village de p\u00eacheurs"],
          ["to have your hands full", "avoir le mains pleines"],
          ["I was expecting", "je m'attendais \u00e0"],
          ["the Rocky Mountains", "les montagnes Rocheuses"],
          ["a lost suitcase", "une valise disparue"],
          ["to take steps", "faire des d\u00e9marches"],
          ["try on a piece of clothing", "essayer un v\u00eatement"],
          ["all around the world", "partout dans le monde"],
          ["we call each other", "on s'appelle"],
          ["find a job", "trouver un emploi"],
          ["she needs", "elle a besoin de"],
          ["half empty", "\u00e0 moiti\u00e9 vide"],
          ["on Thursday we walked on the strip", "le jeudi nous avons march\u00e9 sur le strip"],
          ["after the sun rose", "apr\u00e8s le lever du soleil"],
          ["the mountains were dispersed", "les montagnes \u00e9taient dispers\u00e9es"],
          ["we hired an instructor", "nous avons embouch\u00e9 un instructeur"],
          ["the first thing he showed us", "la premiere chose qu'il nous a montr\u00e9"],
          ["it helped me", "\u00e7a m'a aid\u00e9"],
          ["for an actual game", "pour un vrai joue"],
          ["when we flew to Las Vegas", "quand nous avons vol\u00e9 en Las Vegas"],
          ["cheap", "bon march\u00e9"],
          ["to have nightmares", "faire des cauchemars"],
          ["in life", "dans la vie"],
          ["it will take 10 minutes", "\u00e7a va prendre dix minutes"],
          ["how much time", "combien de temps"],
          ["before playing", "avant de jouer"],
          ["it could take a while", "\u00e7a risque d'\u00eatre long"],
          ["a single parent family", "une famille monoparentale"],
          ["to put up for sale", "mettre en vendre"],
          ["a vision of success", "une vision du succ\u00e8s"],
          ["to have time", "avoir du temps"],
          ["to enrich my life", "m'enrichir personnellement"],
          ["give me a smile", "me donner un sourire"],
          ["I am frustrated", "je suis frustr\u00e9"],
          ["take a lap", "faire un tour"],
          ["they(m) live longer", "ils vivent plus longtemps"],
          ["climate change", "changement climatique"],
          ["I practised", "j'ai pratiqu\u00e9"],
          ["I tried", "j'ai essay\u00e9"],
          ["sometimes I was correct", "parfois j'\u00e9tait correct"],
          ["inflate a balloon", "gonfler un ballon"],
          ["blow out a candle", "souffler une bougie"],
          ["late in the morning", "en fin de matin\u00e9e"],
          ["would that be okay with you", "est-ce que \u00e7a vous convient"],
          ["I remembered (passe compose)", "je me suis souvenu"],
          ["when he had to leave", "quand il a d\u00fb partir"],
          ["it's not the same", "ce n'est pas la m\u00eame"],
          ["when the police", "quand la police"],
          ["when the police officers", "quand les policiers"],
          ["drug dealers", "trafiquants de drogue"],
          ["in canada", "au canada"],
          ["scientific experiements", "exp\u00e9riences scientifiques"],
          ["safe injection sites", "sites d'injection s\u00fbrs"],
          ["they have a really nice place", "ils ont un endroit vraiment beau"],
          ["they have one acre of land", "ils ont un acre de terrain"],
          ["when the sun sets", "quand le soleil se couche"],
          ["I drank (passe compose)", "j'ai bu"],
          ["the upper lip", "la l\u00e8vre sup\u00e9rieure"],
          ["when I was a child", "quand j'\u00e9tais enfant"],
          ["I drove", "je conduisais"],
          ["a farmer", "un fermier"],
          ["a maze", "un labyrinthe"],
          ["guinea pig", "cochon d'Inde"],
          ["we should", "nous devrions"],
          ["a pile of compost", "une pile \u00e0 compost"],
          ["a compost heap", "un tas de compost"],
          ["I put the grass", "je mets le gazon"],
          ["layers of compost", "couches de compost"],
          ["special characters", "caract\u00e8res sp\u00e9ciaux"],
          ["I placed those stones", "j'ai plac\u00e9 ces pierres"],
          ["y'all have learned your lesson", "vous avez appris votre le\u00e7on"],
          ["we returned from golf", "nous sommes revenus du golf"],
          ["I'm going to give them away", "je vais les donner"],
          ["I'm going to give them away for free", "je vais les donner gratuitement"],
          ["it looks cheap", "\u00e7a a l'air cheap"],
          ["for real professionals", "pour les vrais professionnels"],
          ["when I freeze them", "quand je les cong\u00e8le"],
          ["butter chicken", "poulet au beurre"],
          ["the front nine", "les neuf premiers"],
          ["the back nine", "le neuf de retour"],
          ["when I was a child", "quand j'\u00e9tais un enfant"],
          ["I hate peas", "je d\u00e9teste les pois"],
          ["there are one or two tomatoes that are red", "il y a une ou deux tomates qui sont rouge"],
          ["I am proud of you", "je suis fier de toi"],
          ["for what you get", "pour ce que vous obtenez"],
          ["give me back my toy", "rends-moi mon jouet"],
          ["last Saturday", "samedi dernier"],
          ["ready for them", "fraiment pour eux"],
          ["when he takes the shot", "quand il tire"],
          ["I did not catch the words", "je n'ai pas saisi les mots"],
          ["I didn't think about", "je n'ai pas pens\u00e9"],
          ["this computer had to have the ability to", "cet ordinateur devait avoir la capacit\u00e9 de"],
          ["1990", "mille neuf cent quatre-vingt dix"],
          ["second world war", "deuxi\u00e8me guerre mondiale"],
          ["it was a good day", "c'\u00e9tait une bonne journ\u00e9e"],
          ["I rode my bike", "j'ai fait du v\u00e9lo"],
          ["I rode my horse", "j'ai mont\u00e9 mon cheval"],
          ["I do not have a sweet tooth", "je n'ai pas la dent sucr\u00e9e"],
          ["I want to lose weight", "je veux perdre du poids"],
          ["I read the article", "j'ai lu l'article"],
          ["Tomorrow we will go", "demain nous irons"],
          ["we are going to her friend's house", "nous irons chez son amie"],
          ["apple picking", "cueillette de pommes"],
          ["the apples are spoiled", "les pommes sont g\u00e2t\u00e9es"],
          ["it's nothing (you're welcome)", "de rien"],
          ["it was nothing (you're welcome)", "il n'y a pas de quoi"],
          ["Welcome to Ottawa", "Bienvenue \u00e0 Ottawa"],
          ["I did not feel well", "je ne me sentais pas bien"],
          ["I think it will be fun for my parents", "je pense que ce sera amusant pour mes parents"],
          ["The intention was to do a tour of the East coast with them",
           "L'intention \u00e9tait de faire un tour de la c\u00f4te Est avec eux"],
          ["He plays golf very well", "Il joue tr\u00e8s bien au golf"],
          ["I could not run uphill", "je ne pouvais pas courir en mont\u00e9e"],
          ["I will train with weights (futur simple)", "je m'entra\u00eenais avec des poids"],
          ["we played golf", "nous jouions du golf"],
          ["I had a massage (passe compose)", "j'ai eu un massage"],
          ["just in case", "au cas o\u00f9"],
          ["compared to", "par rapport \u00e0"],
          ["that's scary", "\u00e7a c'est effrayent"],
          ["not a single drop", "pas une seule goutte"],
          ["during the night", "pendant la nuit"],
          ["in my backyard", "dans mon jardin"],
          ["it was bad luck for them", "il \u00e9tait une mauvaise chance pour eux"],
          ["we attended", "nous sommes all\u00e9s"],
          ["the baseball cap", "la casquette de baseball"],
          ["deep waters", "l'eaux profondes"],
          ["boiling water", "l'eau bouillante"],
          ["fifty feet", "cinquante pieds"],
          ["fifty inches", "cinquante pouces"],
          ["we took the ferry", "nous avons pris le ferry"],
          ["hit your target", "frappez votre cible"],
          ["the car I drove", "la voiture que je conduisais"],
          ["safety systems", "syst\u00e8mes de s\u00e9curit\u00e9"],
          ["the flight attendant", "l'h\u00f4tesse de l'air"],
          ["the boarding gate", "la porte d'embarquement"],
          ["a box of food", "une bo\u00EEte de nourriture"],
          ["when we flew to Austrailia", "quand nous avons vol\u00e9 en Australie"],
          ["this morning", "ce matin"],
          ["this afternoon", "cet apr\u00E8s midi"],
          ["this evening", "ce soir"],
          ["the hiker", "le randonneur"],
          ["as soon as", "des que"],
          ["it was really cold", "il faisait vraiment froid"],
          ["it was worth it", "\u00e7a en vaut la peine"],
          ["one day at the beginning", "un jour au debut"],
          ["first of all", "tout d'abord"],
          ["at race pace", "au rythme de la course"],
          ["a car dealership", "un concessionnaire automobile"],
          ["walkout basement", "sous-sol avec acc\u00E8s direct"],
          ["knife throwing", "lancer de couteaux"],
          ["axe throwing", "lancer de hache"],
          ["dog sledding", "chien de tra\u00eeneau"],
          ["Prince Edward Island", "\u00EEle du prince \u00E9douard"],
          ["other things", "d'autres choses"],
          ["that I can point to", "que je peux montrer du doigt"],
          ["the drawer divider (div)", "le diviseur de tiroir"],
          ["the drawer dividers (sep)", "les s\u00E9parateurs de tiroirs"],
          ["the tree has deep roots", "l'arbre a des racines profondes"],
          ["as for the cost of tea in China, who cares?", "quant au co\u00fbt du th\ue009 en Chine, qui s'en soucie?"],
          ["a t-shirt has short sleeves", "un t-shirt a des manches courtes"],
          ["good shot (golf)", "bon coup"],
          ["a masters degree", "une ma\u00eetrise"],
          ["the classifieds", "les petites annonces"],
          ["rock climbing", "de l'escalade"],
          ["I feel bad for her", "je me sens mal pour elle"],
          ["I feel bad for him", "je me sens mal pour lui"],
          ["he retired", "il a pris sa retraite"],
          ["last year", "l'ann\u00e9e derni\u00e8re"],
          ["stuck in the elevator", "coinc\u00e9 dans l'ascenseur"],
          ["I wear tights", "je porte des collantes"],
          ["you can go straight through", "tu peux passer tout droit"],
          ]

nouns = [ ["the coal", "le charbon"],
          ["the bridge", "le pont"],
          ["the cement", "le ciment"],
          ["the flyash", "les cendres volantes"],
          ["the mine", "la mien"],
          ["the amount", "la montant"],
          ["the electricity", "l'\u00E9lectricit\u00E9"],
          ["the hardwood", "le bois dur"],
          ["the softwood", "le bois tendre"],
          ["the emergency", "l'urgence"],
          ["the tax", "la taxe"],
          ["the taxes", "les imp\u00F4ts"],
          ["the vegetable garden", "le potager"],
          ["the wood chipper", "le broyeur \u00E0 bois"],
          ["the knitting", "le tricotage"],
          ["the flood", "l'inondation"],
          ["the big flood", "la grande inondation"],
          ["today", "aujourd'hui"],
          ["yesterday", "hier"],
          ["tomorrow", "demain"],
          ["the thunder", "le tonnerre"],
          ["the lightning", "l'\u00E9clair"],
          ["the big lightening", "le grand \u00E9clair"],
          ["the basement", "le sous-sol"],
          ["the tree", "l'arbre"],
          ["the shrub", "l'arbuste"],
          ["hindsight", "r\u00E9trospectivement"],
          ["workout", "\u00EAntrainement"],
          ["the weight", "le poids"],
          ["the weights", "les poids"],
          ["the target", "la cible"],
          ["the salesperson", "l'agent de vente"],
          ["the saleswoman", "la vendeuse"],
          ["the vendor", "le vendeur"],
          ["the business", "les affaires"],
          ["trade", "commerce"],
          ["the goal", "le but"],
          ["the firearm", "l'arme \u00E0 feu"],
          ["the small firearm", "la petite arme \u00E0 feu"],
          ["the gun", "le pistolet"],
          ["the pistol", "le pistolet"],
          ["the password", "le mot de passe"],
          ["the username", "le mot d'utilisateur"],
          ["the connection", "le connexion"],
          ["loading", "chargement"],
          ["a run", "une course"],
          ["the checklist", "la liste de contr\u00f4le"],
          ["mechanic (male)", "m\u00E9canicien"],
          ["mechanic (female)", "m\u00E9canicienne"],
          ["the twig", "la brindille"],
          ["the stem", "la tige"],
          ["the leaf", "la feuille"],
          ["the leaves", "les feuilles"],
          ["the lime", "le citron vert"],
          ["outskirts", "p\u00e9ripheri\u00e9"],
          ["the suburb", "la banlieue"],
          ["the shirt", "la chemise"],
          ["firstly", "premierement"],
          ["a hike", "une randonn\u00e9e"],
          ["the car", "la voiture"],
          ["the cooler", "le frigo"],
          ["the windshield", "le pare-brise"],
          ["the suitcase", "la valise"],
          ["the carry on", "le bagage \u00e0 main"],
          ["the big team", "la grande \u00e9quipe"],
          ["the box", "la bo\u00EEte"],
          ["an email", "un courriel"],
          ["India", "Inde"],
          ["either one", "n'importe"],
          ["whichever", "n'importe quel"],
          ["whenever", "n'importe quand"],
          ["whatever", "n'importe quoi"],
          ["between", "entre"],
          ["translation", "traduction"],
          ["recording", "enregistrement"],
          ["health", "sant\u00e9"],
          ["Lyme disease", "maladie de Lyme"],
          ["the bride", "la mari\u00e9e"],
          ["the groom", "le mari\u00e9"],
          ["a stay", "un s\u00e9jour"],
          ["the hat", "le chapeau"],
          ["the maritimes", "les maritimes"],
          ["the big tides", "les grandes mar\u00e9es"],
          ["the still water", "l'eau calme"],
          ["location", "lieu"],
          ["place", "endroit"],
          ["the timing", "le timing"],
          ["remember", "se souvenir"],
          ["church supper", "diner \u00e0 l'\u00e9glise"],
          ["the crab", "le crabe"],
          ["the lobster", "l'homard"],
          ["the scallop", "la p\u00e9toncle"],
          ["the mussel", "la moule"],
          ["the clam", "la palourde"],
          ["the shrimp", "la crevette"],
          ["the dessert", "le dessert"],
          ["my back", "mon dos"],
          ["the stretching", "l'\u00e9tirement"],
          ["a roller coaster", "une montagnes russes"],
          ["power plant", "centrale \u00e9lectrique"],
          ["the snow cones", "les cones de neige"],
          ["the brand", "la marque"],
          ["the day", "le jour"],
          ["the workshop", "l'atelier"],
          ["the small workshop", "le petit atelier"],
          ["a meeting", "une r\u00e9union"],
          ["an appointment", "un rendez-vous"],
          ["free time", "temps libre"],
          ["a coincidence/fate/luck", "une hasard"],
          ["take a break", "pause"],
          ["as for", "quant"],
          ["fishing", "\u00e0 la p\u00eache"],
          ["tie-dye", "teinture au noeud"],
          ["delighted/pleased", "ravie"],
          ["flashes", "clignote"],
          ["police search", "perquisition"],
          ["experienced", "exp\u00e9riment\u00e9"],
          ["spread out", "\u00e9tendu"],
          ["welcome", "bienvenue"],
          ["the flavour", "la saveur"],
          ["the french cooking", "la cuisine fran\u00e7aise"],
          ["the cooking/baking method", "la cuisson"],
          ["the cooking/baking time", "le temps de cuisson"],
          ["a recipe", "une recette"],
          ["low heat", "feu doux"],
          ["medium heat", "feu moyen"],
          ["high heat", "feu vif"],
          ["a teaspoon (measure)", "une cuill\u00e8re \u00e0 caf\u00e9"],
          ["a tablespoon (measure)", "une cuill\u00e8re \u00e0 soupe"],
          ["the ingredients", "les ingr\u00e9dients"],
          ["the big secret ingredient", "le gros ingr\u00e9dient secret"],
          ["meat served raw", "tartare"],
          ["raw (m)", "cru"],
          ["raw (f)", "crue"],
          ["very rare (meat)", "bleu"],
          ["rare meat (meat)", "saignante"],
          ["medium rare (meat)", "\u00e0 point"],
          ["well done (meat)", "bien cuit"],
          ["a soup stock", "un fond"],
          ["a broth", "un bouillon"],
          ["a hint of", "un soup\u00e7on de"],
          ["the breadcrumbs", "la chapelure"],
          ["the dough/paste", "la p\u00e2te"],
          ["a packet of", "un sachet de"],
          ["the baking powder", "la levure chimique"],
          ["the vanilla sugar", "le sucre vanill\u00e9"],
          ["the baking soda", "le bicarbonate de soude"],
          ["an egg yolk", "un jaune d'oeuf"],
          ["the egg whites", "les blancs d'oeufs"],
          ["a bouquet garni", "un bouquet garni"],
          ["the oven", "le four"],
          ["the stovetop", "la plaque chauffante"],
          ["the stove", "la cuisini\u00e8re"],
          ["the oven tray/baking sheet", "la plaque de cuisson"],
          ["a knife", "un couteau"],
          ["a fork", "une fourchette"],
          ["a spoon", "une cuill\u00e8re"],
          ["a plate", "une assiette"],
          ["a bowl", "un bol"],
          ["a glass", "un verre"],
          ["a mug", "une tasse"],
          ["a frying pan", "une po\u00eale"],
          ["a sauce pan", "une casserole"],
          ["a stew pot", "un fait-tout"],
          ["a pot", "un chaudron"],
          ["a lid", "un couvercle"],
          ["a cake mold", "un moule"],
          ["a ladle", "une louche"],
          ["a whisk", "un fouet"],
          ["a rotating whisk", "un batteur"],
          ["a spatula", "une spatule"],
          ["a pressure cooker", "une cocotte-minute"],
          ["a deep fryer", "une friteuse"],
          ["a grater", "une r\u00e2pe"],
          ["an apron", "un tablier"],
          ["a chef's hat", "une toque"],
          ["the chainsaw", "la tron\u00e7onneuse"],
          ["the blade", "la lame"],
          ["sometimes", "quelquefois"],
          ["unhealthy", "malsain"],
          ["healthy", "sain"],
          ["diabetes", "diab\u00e8te"],
          ["habit", "habitude"],
          ["the snack", "le collation"],
          ["temptation", "tentation"],
          ["training (course)", "formation"],
          ["the district", "l'arrondissement"],
          ["the golfer (m)", "le golfeur"],
          ["the golfer (f)", "la golfeuse"],
          ["dating", "sortir avec"],
          ["a hard run", "une course dure"],
          ["the small envelope", "la petite enveloppe"],
          ["the defect", "le d\u00e9faut"],
          ["the small athlete", "le petit athl\u00e8te"],
          ["volunteer (person)", "b\u00e9n\u00e9vole"],
          ["except", "sauf"],
          ["the ticket", "le billet"],
          ["actually", "en r\u00e9alit\u00e9"],
          ["currently", "actuellement"],
          ["the calculation", "le calcul"],
          ["the big computer", "le gros ordinateur"],
          ["the mud", "la boue"],
          ["bugs", "insectes"],
          ["breakfast", "petit-d\u00e9jeuner"],
          ["lunch", "d\u00e9jeuner"],
          ["dinner", "d\u00eener"],
          ["the protein", "la prot\u00e9ine"],
          ["strawberry jam", "confiture de fraises"],
          ["microwave", "micro-ondes"],
          ["measurement", "measure"],
          ["make the most of/benefit/enjoy", "profiter"],
          ["more/still", "encore"],
          ["exactly/absolutely/totally/just right/all done", "tout \u00e0 fait"],
          ["the tip", "le pourboire"],
          ["memories", "souvenirs"],
          ["the soil", "le sol"],
          ["the earth/dirt", "la terre"],
          ["the potting soil", "le terreau"],
          ["beefsteak tomatoes", "tomates coeur de boeuf"],
          ["the wood", "le bois"],
          ["the electrified fence", "la cl\u00f4ture \u00e9lectrifi\u00e9e"],
          ["the deer", "la cerf"],
          ["the tulipe", "la tulipe"],
          ["the root", "la racine"],
          ["the small squirrel", "le petit \u00e9cureuil"],
          ["the fox", "le renard"],
          ["the chipmunk", "le tamia"],
          ["the finger", "le doigt"],
          ["the frost", "le givre"],
          ["the freezer", "la cong\u00e9lateur"],
          ["the grass", "le gazon"],
          ["in the front", "\u00e0 l'avant"],
          ["in the back", "\u00e0 l'arri\u00e8re"],
          ["the mosquitoe", "le moustique"],
          ["the neck guard", "le prot\u00e8ge-cou"],
          ["long-sleeves", "manches longues"],
          ["especially", "surtout"],
          ["sports field", "terrain"],
          ["agricultural field", "champ"],
          ["background (history)", "contexte"],
          ["the vegetable", "le l\u00e9gume"],
          ["ice-cube trays", "plateaux \u00e0 gla\u00e7ons"],
          ["the ice-cube", "le gla\u00e7on"],
          ["the cube", "le cube"],
          ["Ziploc bags", "sacs Ziploc"],
          ["one year (counting)", "un an"],
          ["one year (specific)", "une ann\u00e9e"],
          ["noun", "nom"],
          ["aloud", "\u00e0 haute voix"],
          ["desire/longing", "envie"],
          ["to feel like, to want to", "avoir envie de"],
          ["the swiss chard", "la bette \u00e0 carde"],
          ["the frog", "la grenouille"],
          ["a cough", "une toux"],
          ["what's at stake", "enjeu"],
          ["a beet", "une betterave"],
          ["part/involvement", "implication"],
          ["rallying/mobilization", "mobilisation"],
          ["free vegetables", "l\u00e9gumes gratuits"],
          ["an eggshell", "un coquilles d'ouef"],
          ["an award", "un prix"],
          ["procedure", "proc\u00e9dure"],
          ["a bug (listening device)", "un bug"],
          ["the bottle", "la bouteille"],
          ["alive", "vivant"],
          ["pattern", "mod\u00e8le"],
          ["the button", "le bouton"],
          ["a bird", "un oiseau"],
          ["beliefs", "croyances"],
          ["electric cord", "cordon \u00e9lectrique"],
          ["rare/scarce", "rare"],
          ["environmentalist", "\u00e9cologiste"],
          ["it was okay", "c'\u00e9tait acceptable"],
          ["recovery", "r\u00e9cup\u00e9ration"],
          ["hobby", "passe-temps"],
          ["endgame", "fin de partie"],
          ["market", "march\u00e9"],
          ["a bin", "un bac"],
          ["the plywood", "le contreplaqu\u00e9"],
          ["the lap (body part)", "les genoux"],
          ["the floor", "le plancher"],
          ["the fur", "le fourrure"],
          ["meowing", "miaulement"],
          ["howling", "hurlement"],
          ["in the middle", "au milieu"],
          ["the sentence", "le phrase"],
          ["and yet", "et pourtant"],
          ["a spider", "une araign\u00e9e"],
          ["spiderwebs", "les toiles d'araign\u00e9e"],
          ["jack-o-lantern", "citrouille-lanternes"],
          ["a pumpkin", "une citrouille"],
          ["mainly", "principalement"],
          ["kindergarten", "maternelle"],
          ["elementary school", "\u00e9cole primaire"],
          ["middle school", "\u00e9cole interm\u00e9diaire"],
          ["high school", "\u00e9cole secondaire"],
          ["the candle", "la bougie"],
          ["the candlestick", "la bougeoir"],
          ["the map", "la carte"],
          ["redneck", "plouc"],
          ["attempted", "tent\u00e9"],
          ["the movie", "le film"],
          ["a suggestion", "une suggestion"],
          ["in fact", "en fait"],
          ["the contest", "le concours"],
          ["immune system", "syst\u00e8me immunitaire"],
          ["side effects", "effets secondaires"],
          ["divorced(m)", "divorc\u00e9"],
          ["divorced(f)", "divorc\u00e9e"],
          ["widower", "veuf"],
          ["widow", "veuve"],
          ["childhood", "enfance"],
          ["obsessed", "obs\u00e9d\u00e9"],
          ["because", "parce que"],
          ["since(cause)", "car"],
          ["since(time)", "depuis"],
          ["on average", "en moyenne"],
          ["a market share", "une part de march\u00e9"],
          ["mammals", "mammif\u00e8res"],
          ["the goat", "la ch\u00e8vre"],
          ["the cow", "la vache"],
          ["the sheep", "la brebis"],
          ["the buffalo", "la bufflonne"],
          ["the donkey", "l'\u00e2nesse"],
          ["the room", "la salle"],
          ["the plain", "la plaine"],
          ["the chest(body)", "la poitrine"],
          ["flat", "plate"],
          ["the splint", "l'attelle"],
          ["the left", "la gauche"],
          ["the right (direction)", "la droite"],
          ["a girlfriend", "une copine"],
          ["prejudices", "des pr\u00e9jug\u00e9s"],
          ["a guy", "un gars"],
          ["each", "chaque"],
          ["an employee(m)", "un employ\u00e9"],
          ["an employee(f)", "une employ\u00e9e"],
          ["by hand", "\u00e0 la main"],
          ["the brain", "le cerveau"],
          ["a sweater", "un chandail"],
          ["the size", "la grandeur"],
          ["the furniture", "les meubles"],
          ["the living room", "le salon"],
          ["the kitchen", "la cuisine"],
          ["the retiree(m)", "le retrait\u00e9"],
          ["the retiree(f)", "le retrait\u00e9e"],
          ["the retirees", "les retrait\u00e9s"],
          ["a nurse", "une infirmi\u00e8re"],
          ["a doctor", "un docteur"],
          ["a sled", "un tra\u00eeneau"],
          ["a lighthouse", "un phare"],
          ["a patio", "une terrasse"],
          ["the war", "la guerre"],
          ["the hurricane", "l'ouragan"],
          ["the big hurricane", "le grand ouragan"],
          ["the cargo", "la cargaison"],
          ["the coroner", "le coroner"],
          ["the schedule", "l'horaire"],
          ["the border", "la fronti\u00e9re"],
          ["the painting", "la peinture"],
          ["the mural", "la murale"],
          ["around twenty", "vingtaine"],
          ["around thirty", "trentaine"],
          ["around forty", "quarantaine"],
          ["around fifty", "cinqantaine"],
          ["a scale", "une balance"],
          ["a blood test", "un bilan sanguin"],
          ["the physician", "le physicien"],
          ["the doctor", "le m\u00e9decin"],
          ["the prescription", "la prescription"],
          ["the butler", "le majordome"],
          ["the excursion", "l'excursion"],
          ["the stroller", "la pousette"],
          ["the kangaroo", "le kangourou"],
          ["the wax", "la cire"],
          ["the cash register/checkout", "la caisse"],
          ]

adjectives = [
          ["bilingual", "bilingue"],
          ["the oldest", "le plus vieux"],
          ["extinct(m)", "\u00e9teint"],
          ["extinct(f)", "\u00e9teinte"],
          ["abundantly/thoroughly/without limit", "abondamment"],
          ["straight(m)", "droit"],
          ["straight(f)", "droite"],
          ["tall(m)", "grand"],
          ["tall(f)", "grande"],
          ["deep", "profond"],
          ["terrifying", "terrifiant"],
          ["sufficient", "suffisant"],
          ["recommended", "recommand\u00e9"],
          ["wet", "mouill\u00e9"],
          ["powerful/potent", "puissant"],
          ["fascinating", "fascinant"],
          ["home made (m)", "fait maison"],
          ["home made (f)", "faite maison"],
          ["golden brown (m)", "dor\u00e9"],
          ["golden brown (f)", "dor\u00e9e"],
          ["sweet", "sucr\u00e9"],
          ["salty", "sal\u00e9"],
          ["bankrupt", "faillite"],
          ["proud(m)", "fier"],
          ["proud(f)", "fi\u00e8re"],
          ["far", "loin"],
          ["close/near", "pr\u00e8s"],
          ["consistent(m)", "constant"],
          ["consistent(f)", "constante"],
          ["muddy(m)", "boueux"],
          ["muddy(f)", "boueuse"],
          ["thin", "mince"],
          ["thick(m)", "\u00e9pais"],
          ["thick(f)", "\u00e9paisse"],
          ["crunchy(m)", "croquant"],
          ["crunchy(f)", "croquante"],
          ["high", "haut"],
          ["low", "bas"],
          ["short(m)", "court"],
          ["short(f)", "courte"],
          ["complicated(m)", "compliqu\u00e9"],
          ["complicated(f)", "compliqu\u00e9e"],
          ["famous", "c\u00e9l\u00e8bre"],
          ["frustrating", "frustrant"],
          ["friendly", "amical"],
          ["surprising", "suprenant"],
          ["surprised(m)", "surpris"],
          ["surprised(f)", "surprise"],
          ["responsible", "responsable"],
          ["curious(m)", "curieux"],
          ["curious(f)", "curieuse"],
          ["dry(m)", "sec"],
          ["dry(f)", "s\u00e8che"],
          ["nice", "joli"],
          ["as much", "autant"],
          ["noisy(m)", "bruyant"],
          ["noisy(f)", "bruyante"],
          ["empty", "vide"],
          ["full", "pleine"],
          ["never", "jamais"],
          ["financially", "financi\u00e8rement"],
          ["bright(m)", "lumineux"],
          ["bright(f)", "lumineuse"],
          ["older/elder", "a\u00een\u00e9"],
          ["early", "t\u00F4t"],
          ["earlier", "tant\u00f4t"],
          ["late", "tard"],
          ["mechanical", "m\u00E9canique"],
          ["similar", "similaire"],
          ["first", "en premier"],
          ["secondly", "deuxi\u00e8mement"],
          ["hard (m)", "dur"],
          ["hard (f)", "dure"],
          ["soft(m)", "doux"],
          ["soft(f)", "douce"],
          ["useful", "utile"],
          ["single (not married)", "c\u00e9libataire"],
          ["the same as", "pareil"],
          ["often", "souvent"],
          ["always", "toujours"],
          ["rarely", "rarement"],
          ["almost", "presque"],
          ["hurtful(m)", "blessant"],
          ["hurtful(f)", "blessante"],
          ["sincerely", "sinc\u00e8rement"],
          ["easily offended", "susceptible"],
          ]

verbs = [ ["to enter/input/grasp/grab/seize/hit", "saisir"],
          ["to listen", "\u00e9couter"],
          ["to develop", "se developper"],
          ["to recognize", "reconna\u00eetre"],
          ["to pay", "r\u00e9gler"],
          ["to draw", "dessiner"],
          ["to pursuade", "pursuader"],
          ["to erase", "effacer"],
          ["to turn on", "allumer"],
          ["to hear", "entendre"],
          ["to grow", "pousser"],
          ["to forgive", "pardonner"],
          ["to pull", "tirer"],
          ["to ask for forgiveness", "se faire pardonner"],
          ["to keep", "garder"],
          ["to end/finish", "terminer"],
          ["to pass", "passer"],
          ["to invite", "inviter"],
          ["to resemble", "ressembler"],
          ["to shop", "magasiner"],
          ["to gather/pick", "cueillir"],
          ["to clean", "nettoyer"],
          ["to shoot", "tirer"],
          ["to increase", "augmenter"],
          ["should/must/have to", "devoir"],
          ["to type", "taper"],
          ["to spill/tilt/flip", "basculer"],
          ["to cut", "couper"],
          ["to insert", "ins\u00e9rer"],
          ["to include", "inclure"],
          ["to achieve", "atteindre"],
          ["to manage", "g\u00e9rer"],
          ["to instigate", "inciter"],
          ["to neuter", "st\u00e9riliser"],
          ["to get/obtain/attain", "obtenir"],
          ["to learn", "apprendre"],
          ["to spoil", "se g\u00e2ter"],
          ["to feel", "sentir"],
          ["to stand out", "se demarquer"],
          ["to wish", "souhaiter"],
          ["to return/give something back", "rendre"],
          ["to swing", "balancer"],
          ["to provide", "fournir"],
          ["to send", "envoyer"],
          ["to lean", "pencher"],
          ["to worry", "s'inqui\u00e8ter"],
          ["to fish", "\u00e0 p\u00eacher"],
          ["to soak", "tremper"],
          ["to remove", "enlever"],
          ["to tell", "raconter"],
          ["to unplug", "debrancher"],
          ["to replug", "rebrancher"],
          ["to restart/reset", "red\u00e9marrer"],
          ["to turn on/light up", "alumer"],
          ["to flash", "clignoter"],
          ["to capture", "capturer"],
          ["to conduct", "mener"],
          ["to enjoy", "appr\u00e9cier"],
          ["to gobble/engulf/wolf down", "engloutir"],
          ["to spread out", "\u00e9tendre"],
          ["to lean on", "appuyer"],
          ["to push on", "appuyer sur"],
          ["to fly", "voler"],
          ["to travel", "voyager"],
          ["to judge", "juger"],
          ["to see", "voir"],
          ["to lose", "perdre"],
          ["to cook/bake", "cuire"],
          ["to warm", "chauffer"],
          ["to preheat", "pr\u00e9chauffer"],
          ["to reheat", "r\u00e9chauffer"],
          ["to bring to a boil", "porter \u00e0 \u00e9bullition"],
          ["to boil", "bouillir"],
          ["to simmer", "mijoter"],
          ["to brown", "faire revenir"],
          ["to put into the oven", "enfourner"],
          ["to melt", "fondre"],
          ["to cook in a frying pan", "po\u00ealer"],
          ["to fry", "frire"],
          ["to reduce", "r\u00e9duire"],
          ["to roast", "r\u00f4tir"],
          ["to steam", "cuire \u00e0 la vapeur"],
          ["to cool", "refroidir"],
          ["to let cool", "laisser refroidir"],
          ["to freeze", "congeler"],
          ["to thaw", "d\u00e9congeler"],
          ["to add", "ajouter"],
          ["to add to other ingredients/again", "rajouter"],
          ["to pour", "verser"],
          ["to stir", "remuer"],
          ["to mix", "m\u00e9langer"],
          ["to whip", "fouetter"],
          ["to mix with a blender", "mixer"],
          ["to slice/chop/carve", "d\u00e9couper"],
          ["to chop", "cisler"],
          ["to slice", "trancher"],
          ["to chop/mince", "hacher"],
          ["to stuff", "farcir"],
          ["to sprinkle/dust", "saupoudrer"],
          ["to coat", "enrober"],
          ["to butter/grease", "beurrer"],
          ["to unmold/remove from a pan", "d\u00e9mouler"],
          ["to grate", "r\u00e2per"],
          ["to peel", "\u00e9plucher"],
          ["to season", "assaisonner"],
          ["to spread", "\u00e9taler"],
          ["to knead", "p\u00e9trir"],
          ["to invest", "investir"],
          ["to let sit", "laisser reposer"],
          ["to volunteer", "se porter voluntaire"],
          ["to follow", "suivre"],
          ["to support", "soutenir"],
          ["to believe", "croire"],
          ["to seduce", "s\u00e9duire"],
          ["to crush", "\u00e9craser"],
          ["to recall", "rappeler"],
          ["to cover", "couvrir"],
          ["to kill", "tuer"],
          ["to correct", "corriger"],
          ["to bring/carry/take", "amener"],
          ["to wipe", "essuyer"],
          ["to experiment", "exp\u00e9rimenter"],
          ["to chew", "m\u00e2cher"],
          ["to prevent", "pr\u00e9ventir"],
          ["to maintain", "maintainir"],
          ["to laugh", "rigoler"],
          ["to try", "essayer"],
          ["to practise", "pratiquer"],
          ["to inflate", "gonfler"],
          ["to blow", "souffler"],
          ["to put", "mettre"],
          ["to give", "donner"],
          ["to hate", "d\u00e9tester"]
          ]

contractions = [ ["\u00e2 le", "au"],
                 ["\u00e2 les", "aux"],
                 ["de le", "du"],
                 ["de les", "des"]
               ]

present_verbs = [ ["I run", "je cours"],
                  ["you run", "tu cours"],
                  ["he runs", "il court"],
                  ["she runs", "elle court"],
                  ["we run", "nous courons"],
                  ["y'all run", "vous courez"],
                  ["they(m) run", "ils courent"],
                  ["they(f) run", "elles courent"],
                  ["I see", "je vois"],
                  ["you see", "tu vois"],
                  ["he sees", "il voit"],
                  ["she sees", "elle voit"],
                  ["we see", "nous voyons"],
                  ["y'all see", "vous voyez"],
                  ["they(m) see", "ils voient"],
                  ["they(f) see", "elles voient"],
                  ["I die", "je meurs"],
                  ["you die", "tu meurs"],
                  ["he dies", "il meurt"],
                  ["she dies", "elle meurt"],
                  ["we die", "nous mourons"],
                  ["y'all die", "vous mourez"],
                  ["they(m) die", "ils meurent"],
                  ["they(f) die", "elles meurent"],
                  ["I can", "je peux"],
                  ["Can I", "puis-je"],
                  ["you can", "tu peux"],
                  ["he can", "il peut"],
                  ["she can", "elle peut"],
                  ["we can", "nous pouvons"],
                  ["y'all can", "vous pouvez"],
                  ["they(m) can", "ils pouvent"],
                  ["they(f) can", "elles pouvent"],
                  ["I send", "j'envoie"],
                  ["you send", "tu envoies"],
                  ["he sends", "il envoie"],
                  ["she sends", "elle envoie"],
                  ["we send", "nous envoyons"],
                  ["y'all send", "vous envoyez"],
                  ["they(m) send", "ils envoient"],
                  ["they(f) send", "elles envoient"],
                  ["I have", "j'ai"],
                  ["you have", "tu as"],
                  ["he has", "il a"],
                  ["she has", "elle a"],
                  ["we have", "nous avons"],
                  ["y'all have", "vous avez"],
                  ["they(m) have", "ils ont"],
                  ["they(f) have", "elles ont"],
                  ["I am", "je suis"],
                  ["you are", "tu es"],
                  ["he is", "il est"],
                  ["she is", "elle est"],
                  ["we are", "nous sommes"],
                  ["y'all are", "vous \u00eates"],
                  ["they(m) are", "ils sont"],
                  ["they(f) are", "elles sont"],
                  ["I do", "je fais"],
                  ["you do", "tu fais"],
                  ["he does", "il fait"],
                  ["she does", "elle fait"],
                  ["we do", "nous faisons"],
                  ["y'all do", "vous faites"],
                  ["they(m) do", "ils font"],
                  ["they(f) do", "elles font"],
                  ["I know", "je sais"],
                  ["you know", "tu sais"],
                  ["he knows", "il sait"],
                  ["she knows", "elle sait"],
                  ["we know", "nous savons"],
                  ["y'all know", "vous savez"],
                  ["they(m) know", "ils savent"],
                  ["they(f) know", "elles savent"],
                  ["I come", "je viens"],
                  ["you come", "tu viens"],
                  ["he comes", "il vient"],
                  ["she comes", "elle vient"],
                  ["we come", "nous venons"],
                  ["y'all come", "vous venez"],
                  ["they(m) come", "ils viennent"],
                  ["they(f) come", "elles viennent"],
                  ["I go", "je vais"],
                  ["you go", "tu vas"],
                  ["he goes", "il va"],
                  ["she goes", "elle va"],
                  ["we go", "nous allons"],
                  ["y'all go", "vous allez"],
                  ["they(m) go", "ils vont"],
                  ["they(f) go", "elles vont"],
                  ["I put", "je mets"],
                  ["you put", "tu mets"],
                  ["he puts", "il met"],
                  ["she puts", "elle met"],
                  ["we put", "nous mettons"],
                  ["y'all put", "vous mettez"],
                  ["they(m) put", "ils mettent"],
                  ["they(f) put", "elles mettent"],
                  ["I give", "je donne"],
                  ["you give", "tu donnes"],
                  ["he gives", "il donne"],
                  ["she gives", "elle donne"],
                  ["we give", "nous donnons"],
                  ["y'all give", "vous donnez"],
                  ["they(m) give", "ils donnent"],
                  ["they(f) give", "elles donnent"],
                  ["I grasp", "je saisis"],
                  ["you grasp", "tu saisis"],
                  ["he grasps", "il saisit"],
                  ["she grasps", "elle saisit"],
                  ["we grasp", "nous saisissons"],
                  ["y'all grasp", "vous saisissez"],
                  ["they(m) grasp", "ils saisent"],
                  ["they(f) grasp", "elles saisissent"],
                  ["I must", "je dois"],
                  ["you must", "tu dois"],
                  ["he must", "il doit"],
                  ["she must", "elle doit"],
                  ["we must", "nous devons"],
                  ["y'all must", "vous devez"],
                  ["they(m) must", "ils doivent"],
                  ["they(f) must", "elles doivent"],
                  ["I clean", "je nettoie"],
                  ["you clean", "tu nettoies"],
                  ["he cleans", "il nettoie"],
                  ["she cleans", "elle nettoie"],
                  ["we clean", "nous nettoyons"],
                  ["y'all clean", "vous nettoyez"],
                  ["they(m) clean", "ils nettoient"],
                  ["they(f) clean", "elles nettoient"],
                  ["I increase", "j'augmente"],
                  ["you increase", "tu augmentes"],
                  ["he increases", "il augmente"],
                  ["she increases", "elle augmente"],
                  ["we increase", "nous augmentons"],
                  ["y'all increase", "vous augmentez"],
                  ["they(m) increase", "ils augmentent"],
                  ["they(f) increase", "elles augmentent"],
                  ["I gather", "je cueille"],
                  ["you gather", "tu cueilles"],
                  ["he gathers", "il cueille"],
                  ["she gathers", "elle cueille"],
                  ["we gather", "nous cueillons"],
                  ["y'all gather", "vous cueillez"],
                  ["they(m) gather", "ils cueillent"],
                  ["they(f) gather", "elles cueillent"],
                  ["I manage", "je g\u00e8re"],
                  ["you manage", "tu g\u00e8res"],
                  ["he manages", "il g\u00e8re"],
                  ["she manages", "elle g\u00e8re"],
                  ["we manage", "nous g\u00e9rons"],
                  ["y'all manage", "vous g\u00e9rez"],
                  ["they(m) manage", "ils g\u00e8rent"],
                  ["they(f) manage", "elles g\u00e8rent"],
                  ["I instigate", "j'incite"],
                  ["you instigate", "tu incites"],
                  ["he instigates", "il incite"],
                  ["she instigates", "elle incite"],
                  ["we instigate", "nous incitons"],
                  ["y'all instigate", "vous incitez"],
                  ["they(m) instigate", "ils incitent"],
                  ["they(f) instigate", "elles incitent"],
                  ["I include", "j'inclus"],
                  ["you include", "tu inclus"],
                  ["he includes", "il inclut"],
                  ["she includes", "elle inclut"],
                  ["we include", "nous incluons"],
                  ["y'all include", "vous incluez"],
                  ["they(m) include", "ils incluent"],
                  ["they(f) include", "elles incluent"],
                  ["I feel", "je me sens"],
                  ["you feel", "tu te sens"],
                  ["he feels", "il se sent"],
                  ["she feels", "elle se sent"],
                  ["we feel", "nous nous sentons"],
                  ["y'all feel", "vous vous sentez"],
                  ["they(m) feel", "ils se sentent"],
                  ["they(f) feel", "elles se sentent"],
                  ["I remember", "je me souviens"],
                  ["you remember", "tu te souviens"],
                  ["he remembers", "il se souvient"],
                  ["she remembers", "elle se souvient"],
                  ["we remember", "nous nous souvienons"],
                  ["y'all remember", "vous vous souvienez"],
                  ["they(m) remember", "ils se souvienent"],
                  ["they(f) remember", "elles se souvienent"],
                  ["I spread", "j'\u00e9tale"],
                  ["you spread", "tu \u00e9tales"],
                  ["he spreads", "il \u00e9tale"],
                  ["she spreads", "elle \u00e9tale"],
                  ["we spread", "nous \u00e9talons"],
                  ["y'all spread", "vous \u00e9talez"],
                  ["they(m) spread", "ils \u00e9talent"],
                  ["they(f) spread", "elles \u00e9talent"],
                ]

imparfait_verbs = [ ["I ran", "je courais"],
                    ["you ran", "tu courais"],
                    ["he ran", "il courait"],
                    ["she ran", "elle courait"],
                    ["we ran", "nous courions"],
                    ["y'all ran", "vous couriez"],
                    ["they(m) ran", "ils couraient"],
                    ["they(f) ran", "elles couraient"],
                    ["I saw", "je voyais"],
                    ["you saw", "tu voyais"],
                    ["he saw", "il voyait"],
                    ["she saw", "elle voyait"],
                    ["we saw", "nous voyions"],
                    ["y'all saw", "vous voyiez"],
                    ["they(m) saw", "ils voyaient"],
                    ["they(f) saw", "elles voyaient"],
                    ["I died", "je mourais"],
                    ["you died", "tu mourais"],
                    ["he died", "il mourait"],
                    ["she died", "elle mourait"],
                    ["we died", "nous mourions"],
                    ["y'all died", "vous mouriez"],
                    ["they(m) died", "ils mouraient"],
                    ["they(f) died", "elles mouraient"],
                    ["I could", "je pouvais"],
                    ["you could", "tu pouvais"],
                    ["he could", "il pouvait"],
                    ["she could", "elle pouvait"],
                    ["we could", "nous pouvions"],
                    ["y'all could", "vous pouviez"],
                    ["they(m) could", "ils pouvaient"],
                    ["they(f) could", "elles pouvaient"],
                    ["I sent", "j'envoyais"],
                    ["you sent", "tu envoyais"],
                    ["he sent", "il envoyait"],
                    ["she sent", "elle envoyait"],
                    ["we sent", "nous envoyions"],
                    ["y'all sent", "vous envoyiez"],
                    ["they(m) sent", "ils envoyaient"],
                    ["they(f) sent", "elles envoyaient"],
                    ["I had", "j'avais"],
                    ["you had", "tu avais"],
                    ["he had", "il avait"],
                    ["she had", "elle avait"],
                    ["we had", "nous avions"],
                    ["y'all had", "vous aviez"],
                    ["they(m) had", "ils avaient"],
                    ["they(f) had", "elles avaient"],
                    ["I was", "j'\u00e9tais"],
                    ["you were", "tu \u00e9tais"],
                    ["he was", "il \u00e9tait"],
                    ["she was", "elle \u00e9tait"],
                    ["we were", "nous \u00e9tions"],
                    ["y'all were", "vous \u00e9tiez"],
                    ["they(m) were", "ils \u00e9taient"],
                    ["they(f) were", "elles \u00e9taient"],
                    ["I did", "je faisais"],
                    ["you did", "tu faisais"],
                    ["he did", "il faisait"],
                    ["she did", "elle faisait"],
                    ["we did", "nous faisions"],
                    ["y'all did", "vous faisiez"],
                    ["they(m) did", "ils faisaient"],
                    ["they(f) did", "elles faisaient"],
                    ["I knew", "je savais"],
                    ["you knew", "tu savais"],
                    ["he knew", "il savait"],
                    ["she knew", "elle savait"],
                    ["we knew", "nous savions"],
                    ["y'all knew", "vous saviez"],
                    ["they(m) knew", "ils savaient"],
                    ["they(f) knew", "elles savaient"],
                    ["I came", "je venais"],
                    ["you came", "tu venais"],
                    ["he came", "il venait"],
                    ["she came", "elle venait"],
                    ["we came", "nous venions"],
                    ["y'all came", "vous veniez"],
                    ["they(m) came", "ils venaient"],
                    ["they(f) came", "elles venaient"],
                    ["I went", "j'allais"],
                    ["you went", "tu allais"],
                    ["he went", "il allait"],
                    ["she went", "elle allait"],
                    ["we went", "nous allions"],
                    ["y'all went", "vous alliez"],
                    ["they(m) went", "ils allaient"],
                    ["they(f) went", "elles allaient"],
                    ["I put", "je mettais"],
                    ["you put", "tu mettais"],
                    ["he puts", "il mettait"],
                    ["she puts", "elle mettait"],
                    ["we put", "nous mettions"],
                    ["y'all put", "vous mettiez"],
                    ["they(m) put", "ils mettaient"],
                    ["they(f) put", "elles mettaient"],
                    ["I gave", "je donnais"],
                    ["you gave", "tu donnais"],
                    ["he gave", "il donnait"],
                    ["she gave", "elle donnait"],
                    ["we gave", "nous donnions"],
                    ["y'all gave", "vous donniez"],
                    ["they(m) gave", "ils donnaient"],
                    ["they(f) gave", "elles donnaient"],
                    ["I grasped", "je saisissais"],
                    ["you grasped", "tu saisissais"],
                    ["he grasped", "il saisissait"],
                    ["she grasped", "elle saisissait"],
                    ["we grasped", "nous saisissions"],
                    ["y'all grasped", "vous saisissiez"],
                    ["they(m) grasped", "ils saisissaient"],
                    ["they(f) grasped", "elles saisissaient"],
                    ["I had to", "je devais"],
                    ["you had to", "tu devais"],
                    ["he had to", "il devait"],
                    ["she had to", "elle devait"],
                    ["we had to", "nous devions"],
                    ["y'all had to", "vous deviez"],
                    ["they(m) had to", "ils devaient"],
                    ["they(f) had to", "elles devaient"],
                    ["I cleaned", "je nettoyais"],
                    ["you cleaned", "tu nettoyais"],
                    ["he cleaned", "il nettoyait"],
                    ["she cleaned", "elle nettoyait"],
                    ["we cleaned", "nous nettoyions"],
                    ["y'all cleaned", "vous nettoyiez"],
                    ["they(m) cleaned", "ils nettoyaient"],
                    ["they(f) cleaned", "elles nettoyaient"],
                    ["I increased", "j'augmentais"],
                    ["you increased", "tu augmentais"],
                    ["he increased", "il augmentait"],
                    ["she increased", "elle augmentait"],
                    ["we increased", "nous augmentions"],
                    ["y'all increased", "vous augmentiez"],
                    ["they(m) increased", "ils augmentaient"],
                    ["they(f) increased", "elles augmentaient"],
                    ["I gathered", "je cueillais"],
                    ["you gathered", "tu cueillais"],
                    ["he gathered", "il cueillait"],
                    ["she gathered", "elle cueillait"],
                    ["we gathered", "nous cueillions"],
                    ["y'all gathered", "vous cueilliez"],
                    ["they(m) gathered", "ils cueillaient"],
                    ["they(f) gathered", "elles cueillaient"],
                    ["I managed", "je g\u00e9rais"],
                    ["you managed", "tu g\u00e9rais"],
                    ["he managed", "il g\u00e9rait"],
                    ["she managed", "elle g\u00e9rait"],
                    ["we managed", "nous g\u00e9rions"],
                    ["y'all managed", "vous g\u00e9riez"],
                    ["they(m) managed", "ils g\u00e9raient"],
                    ["they(f) managed", "elles g\u00e9raient"],
                    ["I incited", "j'incitais"],
                    ["you incited", "tu incitais"],
                    ["he incited", "il incitait"],
                    ["she incited", "elle incitait"],
                    ["we incited", "nous incitions"],
                    ["y'all incited", "vous incitiez"],
                    ["they(m) incited", "ils incitaient"],
                    ["they(f) incited", "elles incitaient"],
                    ["I included", "j'incluais"],
                    ["you included", "tu incluais"],
                    ["he included", "il incluait"],
                    ["she included", "elle incluait"],
                    ["we included", "nous incluions"],
                    ["y'all included", "vous incluiez"],
                    ["they(m) included", "ils incluaient"],
                    ["they(f) included", "elles incluaient"],
                    ["I felt", "je me sentais"],
                    ["you felt", "tu te sentais"],
                    ["he felt", "il se sentait"],
                    ["she felt", "elle se sentait"],
                    ["we felt", "nous nous sentions"],
                    ["y'all felt", "vous vous sentiez"],
                    ["they(m) felt", "ils se sentaient"],
                    ["they(f) felt", "elles se sentaient"],
                    ["I remembered", "je me souvenais"],
                    ["you remembered", "tu te souvenais"],
                    ["he remembered", "il se souvenait"],
                    ["she remembered", "elle se souvenait"],
                    ["we remembered", "nous nous souvenions"],
                    ["y'all remembered", "vous vous souveniez"],
                    ["they(m) remembered", "ils se souvenaient"],
                    ["they(f) remembered", "elles se souvenaient"],
                    ["I spread", "j'\u00e9talais"],
                    ["you spread", "tu \u00e9talais"],
                    ["he spread", "il \u00e9talait"],
                    ["she spread", "elle \u00e9talait"],
                    ["we spread", "nous \u00e9talions"],
                    ["y'all spread", "vous \u00e9taliez"],
                    ["they(m) spread", "ils \u00e9talaient"],
                    ["they(f) spread", "elles \u00e9talaient"],
                  ]

futur_simple_verbs = [
                    ["I will run", "je courrai"],
                    ["you will run", "tu courras"],
                    ["he will run", "il courra"],
                    ["she will run", "elle courra"],
                    ["we will run", "nous courrons"],
                    ["y'all will run", "vous courrez"],
                    ["they(m) will run", "ils courront"],
                    ["they(f) will run", "elles courront"],
                    ["I will see", "je verrai"],
                    ["you will see", "tu verras"],
                    ["he will see", "il verra"],
                    ["she will see", "elle verra"],
                    ["we will see", "nous verrons"],
                    ["y'all will see", "vous verrez"],
                    ["they(m) will see", "ils verront"],
                    ["they(f) will see", "elles verront"],
                    ["I will die", "je mourrai"],
                    ["you will die", "tu mourras"],
                    ["he will die", "il mourra"],
                    ["she will die", "elle mourra"],
                    ["we will die", "nous mourrons"],
                    ["y'all will die", "vous mourrez"],
                    ["they(m) will die", "ils mourront"],
                    ["they(f) will die", "elles mourront"],
                    ["I could", "je pourrai"],
                    ["you could", "tu pourras"],
                    ["he could", "il pourra"],
                    ["she could", "elle pourra"],
                    ["we could", "nous pourrons"],
                    ["y'all could", "vous pourrez"],
                    ["they(m) could", "ils pourront"],
                    ["they(f) could", "elles pourront"],
                    ["I will send", "j'enverrai"],
                    ["you will send", "tu enverras"],
                    ["he will send", "il enverra"],
                    ["she will send", "elle enverra"],
                    ["we will send", "nous enverrons"],
                    ["y'all will send", "vous enverrez"],
                    ["they(m) will send", "ils enverront"],
                    ["they(f) will send", "elles enverront"],
                    ["I will have", "j'aurai"],
                    ["you will have", "tu auras"],
                    ["he will have", "il aura"],
                    ["she will have", "elle aura"],
                    ["we will have", "nous aurons"],
                    ["y'all will have", "vous aurez"],
                    ["they(m) will have", "ils auront"],
                    ["they(f) will have", "elles auront"],
                    ["I will be", "je serai"],
                    ["you will be", "tu seras"],
                    ["he will be", "il sera"],
                    ["she will be", "elle sera"],
                    ["we will be", "nous serons"],
                    ["y'all will be", "vous serez"],
                    ["they(m) will be", "ils seront"],
                    ["they(f) will be", "elles seront"],
                    ["I will do", "je ferai"],
                    ["you will do", "tu feras"],
                    ["he will do", "il fera"],
                    ["she will do", "elle fera"],
                    ["we will do", "nous ferons"],
                    ["y'all will do", "vous ferez"],
                    ["they(m) will do", "ils feront"],
                    ["they(f) will do", "elles feront"],
                    ["I will know", "je saurai"],
                    ["you will know", "tu sauras"],
                    ["he will know", "il saura"],
                    ["she will know", "elle saura"],
                    ["we will know", "nous saurons"],
                    ["y'all will know", "vous saurez"],
                    ["they(m) will know", "ils sauront"],
                    ["they(f) will know", "elles sauront"],
                    ["I will come", "je viendrai"],
                    ["you will come", "tu viendras"],
                    ["he will come", "il viendra"],
                    ["she will come", "elle viendra"],
                    ["we will come", "nous viendrons"],
                    ["y'all will come", "vous viendrez"],
                    ["they(m) will come", "ils viendront"],
                    ["they(f) will come", "elles viendront"],
                    ["I will go", "j'irai"],
                    ["you will go", "tu iras"],
                    ["he will go", "il ira"],
                    ["she will go", "elle ira"],
                    ["we will go", "nous irons"],
                    ["y'all will go", "vous irez"],
                    ["they(m) will go", "ils iront"],
                    ["they(f) will go", "elles iront"],
                    ["I will put", "je mettrai"],
                    ["you will put", "tu mettras"],
                    ["he will put", "il mettra"],
                    ["she will put", "elle mettra"],
                    ["we will put", "nous mettrons"],
                    ["y'all will put", "vous mettrez"],
                    ["they(m) will put", "ils mettront"],
                    ["they(f) will put", "elles mettront"],
                    ["I will give", "je donnerai"],
                    ["you will give", "tu donneras"],
                    ["he will give", "il donnera"],
                    ["she will give", "elle donnera"],
                    ["we will give", "nous donnerons"],
                    ["y'all will give", "vous donnerez"],
                    ["they(m) will give", "ils donneront"],
                    ["they(f) will give", "elles donneront"],
                    ["I will grasp", "je saisirai"],
                    ["you will grasp", "tu saisiras"],
                    ["he will grasp", "il saisira"],
                    ["she will grasp", "elle saisira"],
                    ["we will grasp", "nous saisirons"],
                    ["y'all will grasp", "vous saisirez"],
                    ["they(m) will grasp", "ils saisiront"],
                    ["they(f) will grasp", "elles saisiront"],
                    ["I will have to", "je devrai"],
                    ["you will have to", "tu devras"],
                    ["he will have to", "il devra"],
                    ["she will have to", "elle devra"],
                    ["we will have to", "nous devrons"],
                    ["y'all will have to", "vous devrez"],
                    ["they(m) will have to", "ils devront"],
                    ["they(f) will have to", "elles devront"],
                    ["I will clean", "je nettoierai"],
                    ["you will clean", "tu nettoieras"],
                    ["he will clean", "il nettoiera"],
                    ["she will clean", "elle nettoiera"],
                    ["we will clean", "nous nettoierons"],
                    ["y'all will clean", "vous nettoierez"],
                    ["they(m) will clean", "ils nettoieront"],
                    ["they(f) will clean", "elles nettoieront"],
                    ["I will increase", "j'augmenterai"],
                    ["you will increase", "tu augmenteras"],
                    ["he will increase", "il augmentera"],
                    ["she will increase", "elle augmentera"],
                    ["we will increase", "nous augmenterons"],
                    ["y'all will increase", "vous augmenterez"],
                    ["they(m) will increase", "ils augmenteront"],
                    ["they(f) will increase", "elles augmenteront"],
                    ["I will gather", "je cueillerai"],
                    ["you will gather", "tu cueilleras"],
                    ["he will gather", "il cueillera"],
                    ["she will gather", "elle cueillera"],
                    ["we will gather", "nous cueillerons"],
                    ["y'all will gather", "vous cueillerez"],
                    ["they(m) will gather", "ils cueilleront"],
                    ["they(f) will gather", "elles cueilleront"],
                    ["I will manage", "je g\u00e9rerai"],
                    ["you will manage", "tu g\u00e9reras"],
                    ["he will manage", "il g\u00e9rera"],
                    ["she will manage", "elle g\u00e9rera"],
                    ["we will manage", "nous g\u00e9rerons"],
                    ["y'all will manage", "vous g\u00e9rerez"],
                    ["they(m) will manage", "ils g\u00e9reront"],
                    ["they(f) will manage", "elles g\u00e9reront"],
                    ["I will incite", "j'inciterai"],
                    ["you will incite", "tu inciteras"],
                    ["he will incite", "il incitera"],
                    ["she will incite", "elle incitera"],
                    ["we will incite", "nous inciterons"],
                    ["y'all will incite", "vous inciterez"],
                    ["they(m) will incite", "ils inciteront"],
                    ["they(f) will incite", "elles inciteront"],
                    ["I will include", "j'inclurai"],
                    ["you will include", "tu incluras"],
                    ["he will include", "il inclura"],
                    ["she will include", "elle inclura"],
                    ["we will include", "nous inclurons"],
                    ["y'all will include", "vous inclurez"],
                    ["they(m) will include", "ils incluront"],
                    ["they(f) will include", "elles incluront"],
                    ["I will feel", "je me sentirai"],
                    ["you will feel", "tu te sentiras"],
                    ["he will feel", "il se sentira"],
                    ["she will feel", "elle se sentira"],
                    ["we will feel", "nous nous sentirons"],
                    ["y'all will feel", "vous vous sentirez"],
                    ["they(m) will feel", "ils se sentiront"],
                    ["they(f) will feel", "elles se sentiront"],
                    ["I will remember", "je me souviendrai"],
                    ["you will remember", "tu te souviendras"],
                    ["he will remember", "il se souviendra"],
                    ["she will remember", "elle se souviendra"],
                    ["we will remember", "nous nous souviendrons"],
                    ["y'all will remember", "vous vous souviendrez"],
                    ["they(m) will remember", "ils se souviendront"],
                    ["they(f) will remember", "elles se souviendront"],
                    ["I will spread", "j'\u00e9talerai"],
                    ["you will spread", "tu \u00e9taleras"],
                    ["he will spread", "il \u00e9talera"],
                    ["she will spread", "elle \u00e9talera"],
                    ["we will spread", "nous \u00e9talerons"],
                    ["y'all will spread", "vous \u00e9talerez"],
                    ["they(m) will spread", "ils \u00e9taleront"],
                    ["they(f) will spread", "elles \u00e9taleront"],
                  ]

passe_compose_verbs = [
                    ["I ran", "j'ai couru"],
                    ["you ran", "tu as couru"],
                    ["he ran", "il a couru"],
                    ["she ran", "elle a couru"],
                    ["we ran", "nous avons couru"],
                    ["y'all ran", "vous avez couru"],
                    ["they(m) ran", "ils ont couru"],
                    ["they(f) ran", "elles ont couru"],
                    ["I saw", "j'ai vu"],
                    ["you saw", "tu as vu"],
                    ["he saw", "il a vu"],
                    ["she saw", "elle a vu"],
                    ["we saw", "nous avons vu"],
                    ["y'all saw", "vous avez vu"],
                    ["they(m) saw", "ils ont vu"],
                    ["they(f) saw", "elles ont vu"],
                    ["I died(m)", "je suis mort"],
                    ["you died(m)", "tu es mort"],
                    ["he died(m)", "il est mort"],
                    ["we died(m)", "nous sommes morts"],
                    ["y'all died(m)", "vous \u00eates morts"],
                    ["they(m) died", "ils sont morts"],
                    ["I died(f)", "je suis morte"],
                    ["you died(f)", "tu es morte"],
                    ["she died(f)", "elle est morte"],
                    ["we died(f)", "nous sommes mortes"],
                    ["y'all died(f)", "vous \u00eates mortes"],
                    ["they(f) died", "elles sont mortes"],
                    ["I could", "j'ai pu"],
                    ["you could", "tu as pu"],
                    ["he could", "il a pu"],
                    ["she could", "elle a pu"],
                    ["we could", "nous avons pu"],
                    ["y'all could", "vous avez pu"],
                    ["they(m) could", "ils ont pu"],
                    ["they(f) could", "elles ont pu"],
                    ["I sent", "j'ai envoy\u00e9"],
                    ["you sent", "tu as envoy\u00e9"],
                    ["he sent", "il a envoy\u00e9"],
                    ["she sent", "elle a envoy\u00e9"],
                    ["we sent", "nous avons envoy\u00e9"],
                    ["y'all sent", "vous avez envoy\u00e9"],
                    ["they(m) sent", "ils ont envoy\u00e9"],
                    ["they(f) sent", "elles ont envoy\u00e9"],
                    ["I had", "j'ai eu"],
                    ["you had", "tu as eu"],
                    ["he had", "il a eu"],
                    ["she had", "elle a eu"],
                    ["we had", "nous avons eu"],
                    ["y'all had", "vous avez eu"],
                    ["they(m) had", "ils ont eu"],
                    ["they(f) had", "elles ont eu"],
                    ["I was", "j'ai \u00e9t\u00e9"],
                    ["you were", "tu as \u00e9t\u00e9"],
                    ["he was", "il a \u00e9t\u00e9"],
                    ["she was", "elle a \u00e9t\u00e9"],
                    ["we were", "nous avons \u00e9t\u00e9"],
                    ["y'all were", "vous avez \u00e9t\u00e9"],
                    ["they(m) were", "ils ont \u00e9t\u00e9"],
                    ["they(f) were", "elles ont \u00e9t\u00e9"],
                    ["I did", "j'ai fait"],
                    ["you did", "tu as fait"],
                    ["he did", "il a fait"],
                    ["she did", "elle a fait"],
                    ["we did", "nous avons fait"],
                    ["y'all did", "vous avez fait"],
                    ["they(m) did", "ils ont fait"],
                    ["they(f) did", "elles ont fait"],
                    ["I knew", "j'ai su"],
                    ["you knew", "tu as su"],
                    ["he knew", "il a su"],
                    ["she knew", "elle a su"],
                    ["we knew", "nous avons su"],
                    ["y'all knew", "vous avez su"],
                    ["they(m) knew", "ils ont su"],
                    ["they(f) knew", "elles ont su"],
                    ["I came(m)", "je suis venu"],
                    ["you came(m)", "tu es venu"],
                    ["he came(m)", "il est venu"],
                    ["we came(m)", "nous sommes venus"],
                    ["y'all came(m)", "vous \u00eates venus"],
                    ["they(m) came(m)", "ils sont venus"],
                    ["I came(f)", "je suis venue"],
                    ["you came(f)", "tu es venue"],
                    ["she came(f)", "elle est venue"],
                    ["we came(f)", "nous sommes venues"],
                    ["y'all came(f)", "vous \u00eates venues"],
                    ["they(f) came(f)", "elles sont venues"],
                    ["I went(m)", "je suis all\u00e9"],
                    ["you went(m)", "tu es all\u00e9"],
                    ["he went(m)", "il est all\u00e9"],
                    ["we went(m)", "nous sommes all\u00e9s"],
                    ["y'all went(m)", "vous \u00eates all\u00e9s"],
                    ["they(m) went", "ils sont all\u00e9s"],
                    ["I went(f)", "je suis all\u00e9e"],
                    ["you went(f)", "tu es all\u00e9e"],
                    ["she went(f)", "elle est all\u00e9e"],
                    ["we went(f)", "nous sommes all\u00e9es"],
                    ["y'all went(f)", "vous \u00eates all\u00e9es"],
                    ["they(f) went", "elles sont all\u00e9es"],
                    ["I have put", "j'ai mis"],
                    ["you have put", "tu as mis"],
                    ["he has put", "il a mis"],
                    ["she has put", "elle a mis"],
                    ["we have put", "nous avons mis"],
                    ["y'all have put", "vous avez mis"],
                    ["they(m) have put", "ils ont mis"],
                    ["they(f) have put", "elles ont mis"],
                    ["I have given", "j'ai donn\u00e9"],
                    ["you have given", "tu as donn\u00e9"],
                    ["he has given", "il a donn\u00e9"],
                    ["she has given", "elle a donn\u00e9"],
                    ["we have given", "nous avons donn\u00e9"],
                    ["y'all have given", "vous avez donn\u00e9"],
                    ["they(m) have given", "ils ont donn\u00e9"],
                    ["they(f) have given", "elles ont donn\u00e9"],
                    ["I have grasped", "j'ai saisi"],
                    ["you have grasped", "tu as saisi"],
                    ["he has grasped", "il a saisi"],
                    ["she has grasped", "elle a saisi"],
                    ["we have grasped", "nous avons saisi"],
                    ["y'all have grasped", "vous avez saisi"],
                    ["they(m) have grasped", "ils ont saisi"],
                    ["they(f) have grasped", "elles ont saisi"],
                    ["I had to", "j'ai d\u00fb"],
                    ["you had to", "tu as d\u00fb"],
                    ["he had to", "il a d\u00fb"],
                    ["she had to", "elle a d\u00fb"],
                    ["we had to", "nous avons d\u00fb"],
                    ["y'all had to", "vous avez d\u00fb"],
                    ["they(m) had to", "ils ont d\u00fb"],
                    ["they(f) had to", "elles ont d\u00fb"],
                    ["I cleaned", "j'ai nettoy\u00e9"],
                    ["you cleaned", "tu as nettoy\u00e9"],
                    ["he cleaned", "il a nettoy\u00e9"],
                    ["she cleaned", "elle a nettoy\u00e9"],
                    ["we cleaned", "nous avons nettoy\u00e9"],
                    ["y'all cleaned", "vous avez nettoy\u00e9"],
                    ["they(m) cleaned", "ils ont nettoy\u00e9"],
                    ["they(f) cleaned", "elles ont nettoy\u00e9"],
                    ["I increased", "j'ai augment\u00e9"],
                    ["you increased", "tu as augment\u00e9"],
                    ["he increased", "il a augment\u00e9"],
                    ["she increased", "elle a augment\u00e9"],
                    ["we increased", "nous avons augment\u00e9"],
                    ["y'all increased", "vous avez augment\u00e9"],
                    ["they(m) increased", "ils ont augment\u00e9"],
                    ["they(f) increased", "elles ont augment\u00e9"],
                    ["I gathered", "j'ai cueilli"],
                    ["you gathered", "tu as cueilli"],
                    ["he gathered", "il a cueilli"],
                    ["she gathered", "elle a cueilli"],
                    ["we gathered", "nous avons cueilli"],
                    ["y'all gathered", "vous avez cueilli"],
                    ["they(m) gathered", "ils ont cueilli"],
                    ["they(f) gathered", "elles ont cueilli"],
                    ["I managed", "j'ai g\u00e9r\u00e9"],
                    ["you managed", "tu as g\u00e9r\u00e9"],
                    ["he managed", "il a g\u00e9r\u00e9"],
                    ["she managed", "elle a g\u00e9r\u00e9"],
                    ["we managed", "nous avons g\u00e9r\u00e9"],
                    ["y'all managed", "vous avez g\u00e9r\u00e9"],
                    ["they(m) managed", "ils ont g\u00e9r\u00e9"],
                    ["they(f) managed", "elles ont g\u00e9r\u00e9"],
                    ["I incited", "j'ai incit\u00e9"],
                    ["you incited", "tu as incit\u00e9"],
                    ["he incited", "il a incit\u00e9"],
                    ["she incited", "elle a incit\u00e9"],
                    ["we incited", "nous avons incit\u00e9"],
                    ["y'all incited", "vous avez incit\u00e9"],
                    ["they(m) incited", "ils ont incit\u00e9"],
                    ["they(f) incited", "elles ont incit\u00e9"],
                    ["I included", "j'ai inclus"],
                    ["you included", "tu as inclus"],
                    ["he included", "il a inclus"],
                    ["she included", "elle a inclus"],
                    ["we included", "nous avons inclus"],
                    ["y'all included", "vous avez inclus"],
                    ["they(m) included", "ils ont inclus"],
                    ["they(f) included", "elles ont inclus"],
                    ["I felt(m)", "je me suis senti"],
                    ["you felt(m)", "tu t'es senti"],
                    ["he felt(m)", "il s'est senti"],
                    ["we felt(m)", "nous nous sommes sentis"],
                    ["y'all felt(m)", "vous vous /u00eates sentis"],
                    ["they(m) felt(m)", "ils se sont sentis"],
                    ["I felt(f)", "je me suis sentie"],
                    ["you felt(f)", "tu t'es sentie"],
                    ["he felt(f)", "il s'est sentie"],
                    ["she felt(f)", "elle s'est sentie"],
                    ["we felt(f)", "nous nous sommes senties"],
                    ["y'all felt(f)", "vous vous /u00eates senties"],
                    ["they(f) felt(f)", "elles se sont senties"],
                    ["I remembered(m)", "je me suis souvenu"],
                    ["you remembered(m)", "tu t'es souvenu"],
                    ["he remembered(m)", "il s'est souvenu"],
                    ["we remembered(m)", "nous nous sommes souvenus"],
                    ["y'all remembered(m)", "vous vous \u00eates souvenus"],
                    ["they(m) remembered(m)", "ils se sont souvenus"],
                    ["I remembered(f)", "je me suis souvenue"],
                    ["you remembered(f)", "tu t'es souvenue"],
                    ["she remembered(f)", "elle s'est souvenue"],
                    ["we remembered(f)", "nous nous sommes souvenues"],
                    ["y'all remembered(f)", "vous vous \u00eates souvenues"],
                    ["they(f) remembered(f)", "elles se sont souvenues"],
                    ["I spread", "j'ai \u00e9tal\u00e9"],
                    ["you spread", "tu as \u00e9tal\u00e9"],
                    ["he spread", "il a \u00e9tal\u00e9"],
                    ["she spread", "elle a \u00e9tal\u00e9"],
                    ["we spread", "nous avons \u00e9tal\u00e9"],
                    ["y'all spread", "vous avez \u00e9tal\u00e9"],
                    ["they(m) spread", "ils ont \u00e9tal\u00e9"],
                    ["they(f) spread", "elles ont \u00e9tal\u00e9"],
                  ]


class run_vocab_drill(object):
    def __init__(self, options):
        self.nouns = vocab_drill("Nouns", nouns)
        self.adjectives = vocab_drill("Adjectives", adjectives)
        self.phrases = vocab_drill("Phrases", phrases)
        self.contractions = vocab_drill("Contractions",
                                         contractions)
        self.verbs = vocab_drill("Verbs", verbs)
        self.present_verbs = vocab_drill("Present verbs",
                                          present_verbs)
        self.imparfait_verbs = vocab_drill("Imparfait verbs",
                                            imparfait_verbs)
        self.futur_simple_verbs = vocab_drill("Futur simple verbs",
                                               futur_simple_verbs)
        self.passe_compose_verbs = vocab_drill("Passe compose verbs",
                                                passe_compose_verbs)
        self.drills = []
        if options.nouns:
            self.drills.append(self.nouns)
        if options.adjectives:
            self.drills.append(self.adjectives)
        if options.phrases:
            self.drills.append(self.phrases)
        if options.contractions:
            self.drills.append(self.contractions)
        if options.verbs:
            self.drills.append(self.verbs)
        if options.present_tense:
            self.drills.append(self.present_verbs)
        if options.imparfait_tense:
            self.drills.append(self.imparfait_verbs)
        if options.futur_simple:
            self.drills.append(self.futur_simple_verbs)
        if options.passe_compose:
            self.drills.append(self.passe_compose_verbs)
        self.sample_size = options.sample_size

    def run_drill(self):
        drill_count = 0
        continue_drill = True
        while (continue_drill):
            start_time = datetime.now()
            drill_types = random.sample(self.drills, len(self.drills))
            for drill_type in drill_types:
                continue_drill = drill_type.run_drill(self.sample_size)
                if not continue_drill:
                    break
            if continue_drill:
                drill_count = drill_count + 1
                print("\n***>>> Completed all drills for round %d. <<<***"
                        % drill_count)
                end_time = datetime.now()
                total_secs = math.ceil((end_time-start_time).total_seconds())
                duration = timedelta(seconds=total_secs)
                print("Elapsed time: %s\n" % (str(duration)))

def create_parser():
    parser = OptionParser(description="French vocabulary and verb conjugation drill.  Default settings ask 5 questions selected at random in every subject.  The order of the subjects is randomized.  All questions for a subject must be answered correctly before the next subject is started. Enter 'DROP IT' to drop a question. Enter 'Stop' or CTRL<D> to exit the drill. Special characters may be cut and pasted, or the following notation can be used: '/' for accent ague, '\\' for accent grave, '/\\' for circumflex, and '\\/' for cedilla")
    parser.add_option("-n", "--nouns",
                      action="store_true", dest="nouns", default=False,
                      help="nouns")
    parser.add_option("-a", "--adjectives",
                      action="store_true", dest="adjectives", default=False,
                      help="check vocabulary of french adjectives")
    parser.add_option("-P", "--phrases",
                      action="store_true", dest="phrases", default=False,
                      help="short french phrases")
    parser.add_option("-C", "--contractions",
                      action="store_true", dest="contractions", default=False,
                      help="check vocabulary of french contractions")
    parser.add_option("-v", "--verbs",
                      action="store_true", dest="verbs", default=False,
                      help="verbs infinitif")
    parser.add_option("-p", "--present",
                      action="store_true", dest="present_tense", default=False,
                      help="conjugate verbs in present tense")
    parser.add_option("-f", "--future",
                      action="store_true", dest="futur_simple", default=False,
                      help="conjugate verbs in futur simple")
    parser.add_option("-i", "--imparfait",
                      action="store_true", dest="imparfait_tense", default=False,
                      help="conjugate verbs in imparfait")
    parser.add_option("-c", "--passe_compose",
                      action="store_true", dest="passe_compose", default=False,
                      help="conjugate verbs in passe compose")
    parser.add_option("-s", "--sample_size", type="int",
                      dest="sample_size", default=5,
                      help="set number of questions for each area")
    return parser

def check_options(options):
    if (    not options.nouns
        and not options.adjectives
        and not options.phrases
        and not options.contractions
        and not options.verbs
        and not options.present_tense
        and not options.futur_simple
        and not options.imparfait_tense
        and not options.passe_compose):

        options.nouns = True
        options.adjectives = True
        options.phrases = True
        options.contractions = True
        options.verbs = True
        options.present_tense = True
        options.futur_simple = True
        options.imparfait_tense = True
        options.passe_compose = True
    else:
       # If at least one tense was requested,
       # set the default sample size is check all verbs for each tense.
       if options.sample_size == 5:
           options.sample_size = 0

def main(argv = None):
    logging.basicConfig(level=logging.INFO)
    parser = create_parser()
    if argv is None:
        argv = sys.argv[1:]

    (options, argv) = parser.parse_args(argv)
    if len(argv) != 0:
        print('Must enter at least one thing!')
        print
        parser.print_help()
        return -1

    check_options(options)

    drill = run_vocab_drill(options)
    drill.run_drill()

if __name__ == '__main__':
    sys.exit(main())
